### ISSUE TITLE
ios 9 layout error crash

### ISSUE THREAD

**Issue by Reedyuk** [jessesquires/JSQMessagesViewController#1022]
I know its a little quick, but im getting an exception when displaying the messages view controller.
-[_UILayoutSpacer superview]: unrecognized selector sent to instance 0x148226020

Error in method:
- (void)jsq_updateCollectionViewInsets
line 939 of JSQMessagesViewController

**Comment by mafellows** [comment]
Early indeed, but I'm getting this as well

**Comment by SteffeyDev** [comment]
I have found the same issue, but hadn't realized it was only on iOS 9 though.  I don't have an iPad so only use the simulator.  Have you found anything more about it yet?

**Comment by shaolinjr** [comment]
Have anyone fixed this issue in a different way SteffeyDev said? If yes, please share with us! It's really important..

**Comment by LeoNatan** [comment]
Seems that somehow `_useViewBasedTopAndBottomLayoutGuides` returns true for the messages view controller, which causes the issue.

**Comment by LeoNatan** [comment]
I opened issue rdar://21632022 for this problem. Make sure to duplicate.

**Comment by gsampaio** [comment]
@LeoNatan it would be great if you could add your radar to http://openradar.appspot.com so we can file it as duplicate easier.

**Comment by jessesquires** [comment]
+1 @gsampaio , @LeoNatan

**Comment by LeoNatan** [comment]
Guys, you've convinced me! @gsampaio @jessesquires 

http://www.openradar.me/radar?id=4529690681278464

**Comment by skerkewitz** [comment]
Just tried it on iOS9-beta3 and the issue still exist.

But IMHO the current use of topLayoutGuide is tricky anyway. When the CollectionView will be shown the first time topLayoutGuide.length is 0 even thought my ViewController is shown in a NavigationController. At some point in time later topLayoutGuide.length will be the height of the navigation bar.

So in order to prevent the collection view/cells from jumping around I first set the topContentAdditionalInset to 64.0 to make sure it respect the navigation header and then in viewDidAppear I set the topContentAdditionalInset back to 0 because the topLayoutGuide will take care of the inset for the navigation bar.

All in all I would prefer if JSQ only use the topContentAdditionalInset and does not do some extra magic of its own - so I have to take care of the navigation header height all by myself.

Anyway, I'm getting carried away. :-)

**Comment by dmgts** [comment]
+1 iOS9 beta3 - the issue still exists.

**Comment by LeoNatan** [comment]
Fixed it.

Instead of the line in `viewDidLoad`, use:

```
- (void)loadView
{
	[[[self class] nib] instantiateWithOwner:self options:nil];
}
```

**Comment by dmgts** [comment]
Fixed in iOS beta4

**Comment by jessesquires** [comment]
thanks @dmgts ! closing as fixed.
