### ISSUE TITLE
Layout bug on iPad when contained in split view controller (same issue as #533 again)

### ISSUE THREAD

**Issue by proxxon-re** [jessesquires/JSQMessagesViewController#1042]
See Bug "Layout bug on iPad when contained in split view controller #533" it seems that this problem appears again with the current version of ios8.

The layout using a splitViewController has bugs which can be fixed by rotating the iPAD.

The problem is in JSQMessagesCollectionViewFlowLayout.m

(CGFloat)itemWidth { 
   return CGRectGetWidth(self.collectionView.frame) - self.sectionInset.left - self.sectionInset.right; 
}

self.collectionView.frame returns 320.0 an 703.5 during calculation of bubble sizes. It should always return 703.5 and therefore the bubbles have wrong sizes.

Any idea how to fix it?

**Comment by piercifani** [comment]
It seems that when `JSQMessagesViewController` is being placed in a ViewController container (like `UISplitViewController` or a custom one), the collectionView is not picking up the frame change and invalidating the cached bubble sizes. These bubble sizes are calculated and cached on the first pass on `viewDidLoad` and `viewWillAppear` with a bogus frame, so when AutoLayout kicks in and sets the new frame, the cached sizes are used and a wrong layout is shown.

In order to fix this, I had to resort to use internal JSQ APIs in order to clear the cache (paste this at the end of your viewController's .m) 

``` 
@interface JSQMessagesCollectionViewFlowLayoutInvalidationContext (Fix_For_iPad_Layout)

@property (nonatomic, assign) BOOL invalidateFlowLayoutMessagesCache;

+ (instancetype)context;

@end

@implementation WPCMessagesViewController (Fix_For_iPad_Layout)

- (void)viewDidLayoutSubviews
{
    [super viewDidLayoutSubviews];
    
    JSQMessagesCollectionViewFlowLayoutInvalidationContext *ctx = [JSQMessagesCollectionViewFlowLayoutInvalidationContext context];
    ctx.invalidateFlowLayoutMessagesCache = YES;
    [self.collectionView.collectionViewLayout invalidateLayoutWithContext:ctx];
}

@end
```

Maybe this should be smarter and only invalidate the layout and message cache if there's a frame change, but it's a workaround until we do something smarted about it inside `JSQMessages`

**Comment by proxxon-re** [comment]
Hi Piercifani,

thanks für the infos. I will check this tomorrow and give you a reply.

Alex

**Comment by proxxon-re** [comment]
Hi Piercifani,

i could find time today and your fix works for me. Thank you, seems like the problem could be solved with this trick.

Thanks again for this great pod.

Alex

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
