### ISSUE TITLE
Avatar image circle cropping is slow

### ISSUE THREAD

**Issue by cbowns** [jessesquires/JSQMessagesViewController#1096]
I'm seeing 10–22 msec of work being done when I call `+ (JSQMessagesAvatarImage *)avatarImageWithImage:(UIImage *)image diameter:(NSUInteger)diameter` for an avatar image for a cell. This is on an iPhone 5s on iOS 8.3.

This work is:

- Happening on the main thread
- Taking longer than 16 msec

which all but guarantees that we drop a frame while scrolling.

Bookmarking this so I can come back and do some perf work on it.

**Comment by LeoNatan** [comment]
While there may be room for improvement, you should not be doing this as you scroll anyway. You should create `JSQMessagesAvatarImage` cache as you open your conversation view (or even before), and then store them and reuse them as needed.

**Comment by cbowns** [comment]
That's what I did to mitigate it.

If you all want that to be official, I'll add some documentation to that effect for that particular API and open a PR.

**Comment by LeoNatan** [comment]
Perhaps even better would be caching inside the framework.

**Comment by jessesquires** [comment]
Hey guys — the `JSQMessagesAvatarImageFactory` class doesn't make any claims regarding on which thread it should be used.

You definitely **should not** be calling these methods on every dataSource/delegate callback. And probably not on the main thread. Note that the demo creates these once and caches them, though it does do this on the main thread — that's just because it is a demo app.

There are plenty of great caching libraries available that you could utilize — caching is not a goal of this library.
