### ISSUE TITLE
Custom JSQMessagesLoadEarlierHeaderView crash

### ISSUE THREAD

**Issue by mrojas** [jessesquires/JSQMessagesViewController#1129]
I needed a custom "load earlier" button (really custom) so I implemented a custom nib and the following method:

```swift
override func collectionView(collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, atIndexPath indexPath: NSIndexPath) -> UICollectionReusableView {

        if (self.showLoadEarlierMessagesHeader && kind == UICollectionElementKindSectionHeader) {
            let headerView = self.collectionView.dequeueReusableSupplementaryViewOfKind(UICollectionElementKindSectionHeader, withReuseIdentifier: kLoadMoreHeaderReuseIdentifier, forIndexPath: indexPath) as! ACLoadMoreMessagesHeaderView
            headerView.setLoading(loadingEarlier)
            headerView.onTap = {
                [unowned self]
                (hv: ACLoadMoreMessagesHeaderView) in
                if !self.loadingEarlier {
                    self.loadMoreHeader = hv
                    self.loadingEarlier = true
                    hv.setLoading(self.loadingEarlier)
                    self.loadMoreMessages(true, updateFromServer: true)
                }
            }

            return headerView
        }

        return super.collectionView(collectionView, viewForSupplementaryElementOfKind: kind, atIndexPath: indexPath)
    }
```

The thing is, every now and then while scrolling the collection view I get a crash. It's actually quite easy to reproduce.

*** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /SourceCache/UIKit/UIKit-3318.16.14/UICollectionViewData.m:426

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'layout attributes for supplementary item at index path (<NSIndexPath: 0x170fbc40> {length = 2, path = 0 - 0}) changed from <JSQMessagesCollectionViewLayoutAttributes: 0x1707ac80> index path: (<NSIndexPath: 0x17234790> {length = 2, path = 0 - 0}); element kind: (UICollectionElementKindSectionHeader); frame = (0 0; 320 120);  to <JSQMessagesCollectionViewLayoutAttributes: 0x1722d9d0> index path: (<NSIndexPath: 0x170fbc40> {length = 2, path = 0 - 0}); element kind: (UICollectionElementKindSectionHeader); frame = (0 0; 320 120); zIndex = -1;  without invalidating the layout'

Any ideas why this may happen? I see where zIndex is set to -1 in the code, I just don't understand why is it different (no zIndex in the first case)

**Comment by jessesquires** [comment]
Thanks @mrojas ! Please update the issues after reading the [updated contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md)! :smile:

**Comment by GianniCarlo** [comment]
@mrojas I recently had to develop a custom nib also. I subclassed `JSQMessagesLoadEarlierHeaderView` because at some point I (think) I saw that the library was expecting a custom view of type that type. After that, you have to let the collection view know about your nib in `viewDidLoad()`
```objective-c
[self.collectionView registerNib:[CustomHeaderView nib] 
      forSupplementaryViewOfKind: UICollectionElementKindSectionHeader 
             withReuseIdentifier:[CustomHeaderView headerReuseIdentifier]];
```
If you decide to subclass, don't forget to override `headerReuseIdentifier`
Then in your `JSQMessagesViewController` subclass, in the function override notice that I don't call super
```objective-c
-(UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath{
  UICollectionReusableView *header = [collectionView dequeueReusableSupplementaryViewOfKind:kind withReuseIdentifier:[CustomHeaderView headerReuseIdentifier] forIndexPath:indexPath];
        ((CustomHeaderView *)header).customDelegate = self;
  return header;
}
```
In my case, I needed two different headers, the one provided by the library and my custom one, I had to keep track of the header reuse identifier and when to use which (so I had an if clause in that last function). If you need to use the one given by the library, then you must call super with the same parameters of the function `header = [super collectionView:collectionView viewForSupplementaryElementOfKind:kind atIndexPath:indexPath];`

Hope this helps

**Comment by jessesquires** [comment]
thanks @GianniCarlo !
