### ISSUE TITLE
Send Button not visible next to message input field

### ISSUE THREAD

**Issue by Addadahine** [jessesquires/JSQMessagesViewController#1170]
![photo 19-08-2015 18 23 00](https://cloud.githubusercontent.com/assets/12279610/9365584/3b76775e-46aa-11e5-9d7e-f8ccfe925b48.png)
I have implemented JSQMessagesviewcontroller with the help of NotificationChat from RelatedCode. In my chatview however, only the message input textfield is displayed in the toolbar. The send button is not there! 

Any thoughts?

**Comment by jessesquires** [comment]
Thanks @Addadahine ! :smile: 

Please update the issue after looking at the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md). :smile: 

If this issue is from using the RelatedCode/NotificationChat fork, I can't really help unless you can reproduce this in the demo project here. You should probably open an issue with RelatedCode/NotificationChat.

**Comment by Addadahine** [comment]
Hi Jesse,

Thank you for getting back to me, I have been in touch with RelatedCode and they say I should raise the issue with you.

Any chance you could spare a few minutes to help me with this?

Kind regards,

Sam Addadahine | +44 7852 339 267
Treasurer, Kingston Entrepreneurs
International Business with Law, Kingston Business School

Linkedin
