### ISSUE TITLE
iOS9 crash on JSQMessagesCollectionViewLayoutAttributes.m:44

### ISSUE THREAD

**Issue by kitetaka** [jessesquires/JSQMessagesViewController#1217]
XCode says:
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: messageBubbleFont != nil'

I was using 7.0.0, and iOS 8 no problem, then tried 7.0.2, 7.2.0, all crash at the same Assert line 44. I even tried to set a font there, not working. It's crashing the user experience, would be a huge turn down on the app. please fix .... thanks!

**Comment by eliburke** [comment]
I am experiencing this same error after upgrading from iOS 8.4 to iOS 9, with both 7.2.0, and release_8.0. In my particular case, removing a call in my viewDidAppear to [self scrollToBottomAnimated:animated] "fixed" / mitigated the problem, so it could be related to #1150. It is not actually font related.

I have not had time to explore how it is triggered, but I suspect it is a combination of layout invalidation and bubble resizing. In my app, messages start out encrypted and a one-line placeholder is shown. As messages are decrypted, I invalidate to display the new text. With short message bodies that do not change the layout, there is no crash. When the decrypted messages are longer, it crashes.

**Comment by dpreston10** [comment]
I experience this with some Photo messages. I suspect it does have to do with the resizing. I will remove my call to scrollToBottomAnimated:animated in the meantime.

**Comment by kitetaka** [comment]
Thanks a lot for the prompt help! For the mean time I'll do this, so I can release the app :)

**Comment by jessesquires** [comment]
@kitetaka 

>all crash at the same Assert line 44. 

Which file?

**Comment by eliburke** [comment]
@jessesquires sorry I didn't get back to you yesterday. The Assert is on line 44 of JSQMessagesCollectionViewLayoutAttributes.m in setMessageBubbleFont. The next call up on the stack is from copyWithZone.

**Comment by eliburke** [comment]
I've modified the Demo project to demonstrate this crash. It's branched off release_8.0, compiles for Xcode7, and crashes reliably in the simulator and on device: https://github.com/eliburke/JSQMessagesViewController/tree/scroll_layout_crash

Changes are minimal: I created a loadable subclass of JSQMessages, and trigger a load in messageDataForItemAtIndexPath. 
In viewDidAppear, if you turn off springiness, or remove the scrollToBottomAnimated, it will not crash

**Comment by yproduction** [comment]
I had experienced the same crash.
Avoided it by disabling springiness
i.e.
self.collectionView?.collectionViewLayout.springinessEnabled = false
(where springiness animation is triggered by the scrollToBottomAnimated)

I believe the issue lies in JSQMessagesCollectionViewFlowLayout.m
where the following warnings were shown in XCode 7

- (void)jsq_removeNoLongerVisibleBehaviorsFromVisibleItemsIndexPaths:(NSSet *)visibleItemsIndexPaths
- (void)jsq_adjustSpringBehavior:(UIAttachmentBehavior *)springBehavior forTouchLocation:(CGPoint)touchLocation

/Volumes/Data/Development/XCode/Yun/Yun/JSQMessagesViewController/Layout/JSQMessagesCollectionViewFlowLayout.m:580:43: Initializing 'UICollectionViewLayoutAttributes *__strong' with an expression of incompatible type 'id<UIDynamicItem> _Nullable'

**Comment by vixentael** [comment]
+1 to disable springiness workaround

**Comment by jessesquires** [comment]
Hey @eliburke - The problem is that you are calling `reloadData` and `invalidateLayout` from `messageDataForItemAtIndexPath:`. This is equivalent to calling these methods from `cellForItemAtIndexPath:`. **You cannot do this.** Try this with a vanilla collection view, and you'll also start crashing. This is misusing the UIKit APIs.

Further more, in JSQMessages `messageDataForItemAtIndexPath:` is called from a few other places. Namely, it is called from the layout object during size calculations. Thus, your code is creating multiple race conditions.

This is basically your call tree:

1. cellForItemAtIndexPath --> reloadData --> cellForItemAtIndexPath --> reloadData --> etc.
2. flowLayout calculate bubble size and cache --> invalidate layout --> clear cache --> flowLayout calculate bubble size and cache --> etc.

**Comment by eliburke** [comment]
@jessesquires That's a fair complaint. I took some shortcuts to make a quick demo. 

But whether it's doing decryption, or pulling data from a website or local cache, if I change the cell sizes, sooner or later the collection view must be invalidated and reloaded. If messageDataForItemAtIndexPath can be called any time, in multiple places, when or how is it ever safe to invalidate the layout?

**Comment by jessesquires** [comment]
>when or how is it ever safe to invalidate the layout?

Pretty much anywhere that is **not** inside of a dataSource or delegate method.

**Comment by eliburke** [comment]
https://www.youtube.com/watch?v=vpwxTx4xnJ8

I guess I wasn't clear in what I was saying. I have always understood that it was ok to use dispatch_* or postNotificationName to schedule code to execute outside of a delegate/datasource, back on the main run loop. If you are saying that is an unsafe technique, it seems to me that it would be equally unsafe to do processing on a background thread and use dispatch_* or post a notification to trigger layout invalidation back to the main thread. Both situations could trigger this same race condition. 

For what it's worth, I've re-worked the demo demo project again. It no longer invalidates the layout, or does any work in messageDataForItemAtIndexPath. Instead, in willDisplayCell it changes the cell size the first time it is called. If springiness is enabled, and the view scrolls (via scrollToBottomAnimated) it crashes.

If your answer is still "well duh, don't do that" we can conclude this conversation. I've turned off springiness and that allows me to move forward.

**Comment by kennydust** [comment]
turning off springiness worked for me.

**Comment by jessesquires** [comment]
>If you are saying that is an unsafe technique, it seems to me that it would be equally unsafe to do processing on a background thread and use dispatch_* or post a notification to trigger layout invalidation back to the main thread. Both situations could trigger this same race condition.

No that's not the case. The race condition arises from the fact that *during* execution of `cellForItemAtIndexPath:` you could return from your `dispatch_async` and call `reloadData`. It is possible to overwhelm `UICollectionView` with updates/reloads. This is why `performBatchUpdates:` exists.

There was a very similar question/problem at #1241. See my comment there https://github.com/jessesquires/JSQMessagesViewController/issues/1241#issuecomment-146432281 on how to construct an appropriate flow. Your situation is a bit different, but the concepts are the same.

**Comment by herwangsong** [comment]
turning off springiness can't help me. I don't reloadData in any dataSouce or delegate method.

**Comment by ilyabreev** [comment]
+1 for turning off springiness

**Comment by jessesquires** [comment]
Thanks all! :smile: 

Now tracking this at #1338.

**Comment by sidan5** [comment]
Disabling springiness worked +1

**Comment by icefall** [comment]
turning off springiness worked for me +1
I don't reloadData in any dataSouce or delegate method.
