### ISSUE TITLE
multiple chat bubble styles

### ISSUE THREAD

**Issue by movingdecimals** [jessesquires/JSQMessagesViewController#1233]
In my app I will need one bubble or chat message style for one type of chat and a different bubble for a different type of conversation. For instance one style should not have any avatars, the other one will. One will have time stamps in the cell header, the other won't have timestamps at all.

 Do you have any tips on loading up multiple styles without touching any of the pod's code?

**Comment by GianniCarlo** [comment]
@movingdecimals if it's different styles by conversation and not different styles per bubble *in* a conversation then it's far easier. 

The best approach that I found was to subclass `JSQMessagesCollectionViewCellIncoming` and `JSQMessagesCollectionViewCellOutgoing`. This is very important, because the library is expecting one of those types, you will run into trouble if you subclass from `JSQMessagesCollectionViewCell` directly. BTW, I copied the existing `JSQMessagesCollectionViewCellOutgoing.xib`, `JSQMessagesCollectionViewCellIncoming.xib` and changed/renamed everything and this made it easier for me to start my customization of the cells.

Then in your `JSQMessagesViewController` subclass, register cell identifiers in your `viewDidLoad()` like so:

```objective-c
    self.outgoingCellIdentifier = [CustomCollectionViewCellOutgoing cellReuseIdentifier];
    self.outgoingMediaCellIdentifier = [CustomCollectionViewCellOutgoing mediaCellReuseIdentifier];
    
    [self.collectionView registerNib:[CustomCollectionViewCellOutgoing nib] forCellWithReuseIdentifier:self.outgoingCellIdentifier];
    [self.collectionView registerNib:[CustomCollectionViewCellOutgoing nib] forCellWithReuseIdentifier:self.outgoingMediaCellIdentifier];
    
    self.incomingCellIdentifier = [CustomCollectionViewCellIncoming cellReuseIdentifier];
    self.incomingMediaCellIdentifier = [CustomCollectionViewCellIncoming mediaCellReuseIdentifier];
    
    [self.collectionView registerNib:[CustomCollectionViewCellIncoming nib] forCellWithReuseIdentifier:self.incomingCellIdentifier];
    [self.collectionView registerNib:[CustomCollectionViewCellIncoming nib] forCellWithReuseIdentifier:self.incomingMediaCellIdentifier];
```

Then in `collectionView:cellForItemAtIndexPath:` you can access your custom cell:

```objective-c
//you can add a validation to check if it's outgoing or incoming message
CustomCollectionViewCellOutgoing *cell = (CustomCollectionViewCellOutgoing *)[super collectionView:collectionView cellForItemAtIndexPath:indexPath];
```

Hope this gets you started

**Comment by jessesquires** [comment]
thanks @GianniCarlo !

**Comment by movingdecimals** [comment]
Thank you @GianniCarlo. This was a huge help.

If I want to get rid of the bubble nub for one of the two chat views will I need to subclass the bubble factory?

**Comment by GianniCarlo** [comment]
@movingdecimals well I had to get rid of those too, it's not necessary to subclass the bubble factory, what I did was:
Declare two properties in your `JSQMessagesViewController` subclass
```objective-c
@property (strong, nonatomic) JSQMessagesBubbleImage *outgoingBubbleImageData;
@property (strong, nonatomic) JSQMessagesBubbleImage *incomingBubbleImageData;
```
Then in the `viewDidLoad()` get the required Image data from the bubble factories
```objective-c
//The library provides different types of bubbles like jsq_bubbleCompactTaillessImage
    JSQMessagesBubbleImageFactory *bubbleFactoryOutgoing = [[JSQMessagesBubbleImageFactory alloc] initWithBubbleImage:[UIImage jsq_bubbleCompactTaillessImage] capInsets:UIEdgeInsetsZero];
    JSQMessagesBubbleImageFactory *bubbleFactoryIncoming = [[JSQMessagesBubbleImageFactory alloc] initWithBubbleImage:[UIImage jsq_bubbleCompactTaillessImage] capInsets:UIEdgeInsetsZero];
    //set your bubble color
    self.outgoingBubbleImageData = [bubbleFactoryOutgoing outgoingMessagesBubbleImageWithColor:[UIColor jsq_messageBubbleBlueColor]];
    self.incomingBubbleImageData = [bubbleFactoryIncoming incomingMessagesBubbleImageWithColor:[UIColor jsq_messageBubbleLightGrayColor]];
```
Then you can have something like this for the collectionview
```objective-c
- (id<JSQMessageBubbleImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView messageBubbleImageDataForItemAtIndexPath:(NSIndexPath *)indexPath
{
    /**
     *  You may return nil here if you do not want bubbles.
     *  In this case, you should set the background color of your collection view cell's textView.
     *
     *  Otherwise, return your previously created bubble image data objects.
     */
    
    JSQMessage *message = [self.visibleMessagesArray objectAtIndex:indexPath.item];
    
    if([message.senderId isEqualToString:self.senderId]){
        return self.outgoingBubbleImageData;
    }
    
    return self.incomingBubbleImageData;
}
```

**Comment by GianniCarlo** [comment]
@movingdecimals You can have a third bubble image data, and check another condition inside the last function if that's what you were after.
Cheers!

**Comment by movingdecimals** [comment]
@GianniCarlo I can't tell you how much time you saved me from digging into the code to figure this stuff out. Thank you again !

Our designer just told me that in the next rev we will be hiding the avatar on any concurrent messages. Like you had asked about in the first response. Within the same chat two bubbles from the same user will look different. Any tips on that? 

Hopefully this is my last q. Again, thank you, thank you, thank you.

**Comment by GianniCarlo** [comment]
@movingdecimals glad I was able to help. If you need to hide the avatar for concurrent messages in your `JSQMessagesViewController` you could try messing with the following function
```objective-c
- (id<JSQMessageAvatarImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView avatarImageDataForItemAtIndexPath:(NSIndexPath *)indexPath
{
    /**
     *  Return `nil` here if you do not want avatars.
     *  If you do return `nil`, be sure to do the following in `viewDidLoad`:
     *
     *  self.collectionView.collectionViewLayout.incomingAvatarViewSize = CGSizeZero;
     *  self.collectionView.collectionViewLayout.outgoingAvatarViewSize = CGSizeZero;
     *
     *  It is possible to have only outgoing avatars or only incoming avatars, too.
     */

    JSQMessage *currentMessage = [self.visibleMessagesArray objectAtIndex:indexPath.item];

    if (indexPath.item < self.visibleMessagesArray.count -1) {
        JSQMessage *nextMessage = [self.visibleMessagesArray objectAtIndex:indexPath.item +1];
        //check if next message is from the same user
        if([nextMessage.senderId isEqualToString:currentMessage.senderId]){
             //no avatar for this bubble then
             return nil;
        }
    }
    //your avatars must be of type JSQMessagesAvatarImage
    //check if it's incoming
    if (![currentMessage.senderId isEqualToString:self.senderId]) {
        return self.incomingAvatar;
    }
    
   return self.outgoingAvatar;

}
```
I have not tested this, but it should work. Let me know if this helps you

**Comment by jessesquires** [comment]
Thanks again for helping to answer questions @GianniCarlo ! Very much appreciated. :smile: 

Just a heads up, there are a couple of known issues with customizing avatars. See #491 and #564

**Comment by GianniCarlo** [comment]
@jessesquires glad I can give something back, this library has made my life easier 👍👍

**Comment by movingdecimals** [comment]
Everything is working great except I added typing indicators and those are showing up with the tail'ed bubbles. Any tips on getting the bubble style of the typing indicators to match the chat bubbles?

**Comment by movingdecimals** [comment]
Found the issue. I had set the reuse id in the xib instead of letting the package do it on it's own. I removed that and it is working now. I'm totally tailless now.

**Comment by momone83** [comment]
Hi @GianniCarlo ,
I'm using the library through CocoaPods and everything works properly. But if I try to customize the cells, as in your example, I have problems with the registration of the .nib files. In fact through CocoaPods the library is available as a framework (use_framework!) and for that reason if I use the
 **super.collectionView(collectionView, cellForItemAtIndexPath: indexPath)** 
method, I get the following error:

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle <***BUNDLE NAME***> (loaded)' with name '***NIB NAME***''

The two bundles (in the application bundle and the bundle of the library / framework) are totally independent and therefore there is no way to share xib files.

Have you found a solution to this problem?
Thanks

**Comment by GianniCarlo** [comment]
@momone83 can you tell me what are you trying to achieve exactly? can you post the part of your `viewDidLoad` where you register your .nib files?

**Comment by momone83** [comment]
I must register nib in this way

**self.collectionView.registerNib(UINib(nibName: "ChatMessagesCollectionViewCellOutgoing", bundle: self.nibBundle), forCellWithReuseIdentifier: self.outgoingCellIdentifier)**

If I register nib as in the example

**self.outgoingCellIdentifier = [CustomCollectionViewCellOutgoing cellReuseIdentifier];

    [self.collectionView registerNib:[CustomCollectionViewCellOutgoing nib] forCellWithReuseIdentifier:self.outgoingCellIdentifier];**

I get the following error

**Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle <BUNDLE NAME> (loaded)' with name 'NIB NAME''**

and **self.outgoingCellIdentifier** has the value

**SwiftTools.ChatMessagesCollectionViewCellOutgoing**

**Comment by Nide27** [comment]
Is it possible to have different styles per bubble in a conversation ?

**Comment by UnateD** [comment]
Same question
