### ISSUE TITLE
Avatar Image

### ISSUE THREAD

**Issue by at90vader** [jessesquires/JSQMessagesViewController#1261]
hi!
Is there a way to apply the property "sizeToFit" to the avatar images?

Thank you!

**Comment by carayolthomas** [comment]
Hi there,

What do you want to achieve this way? Whatever this is, I don't think you should do this because all the layout of this library is computed in the `viewDidLoad` method. If you change sizes of subviews, it's not guaranteed that you won't get any UI problems. 

Anyway, you can apply `sizeToFit` to the `cell.avatarImageView` or `cell.avatarContainerView` in the - `(UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath` delegate method.

Just a reference of another issue which I think may be useful for you : #1236 

Hope it helps.

Have a great day!

**Comment by jessesquires** [comment]
Thanks @carayolthomas ! :smile:
