### ISSUE TITLE
Message bubbles too small, text truncated

### ISSUE THREAD

**Issue by machive** [jessesquires/JSQMessagesViewController#1375]
Hello, 
  My message bubbles are too small and the text gets truncated after just a few words. Do I need to include a bubble text size delegate method? This is the second project that I've used JSQMessages in and I didn't have this problem last time. That was in Objective C and I have moved to Swift. 

  Also, the input text view does not clear automatically after pressing the Send button. Do I have to do that too?

  And, for some reason, I cannot get a back button or dismiss button on my MessagesViewController after trying all kinds of things to get a left bar button on the navigation item. The controller is brought up through a Show segue. 

  I have a demo on Weds so I would appreciate any help you could give me. Happy Holidays to all.

**Comment by machive** [comment]
Anybody? anybody?

**Comment by eliburke** [comment]
I think folks are on holiday instead of waiting around to help you, or hoping you'll take the time to look through old issues for your solutions. You can use the is:closed tag on the search field to see them, or clear the is:open tag.

There is no textSize delegate, it is calculated from the text. You may not be setting unique hash values, or If you are changing the value of your text bubbles any time after they are first loaded you may need to invalidate the collection (shown here in ObjC)
```
    JSQMessagesCollectionViewFlowLayoutInvalidationContext *context = [JSQMessagesCollectionViewFlowLayoutInvalidationContext context];
     context.invalidateFlowLayoutMessagesCache = YES;
     [self.collectionView.collectionViewLayout invalidateLayoutWithContext:context];
     [self.collectionView reloadData];
```

To clear the input text, you probably want finishSendingMessageAnimated, or clear it yourself from
inputToolbar.contentView.textView

The missing back button is not a problem with the JSQ view controller, it's probably something about the way you are doing it in your Swift code. Check your constraints and scroll insets, verify that you have a nav controller, try setting the buttons programmatically to see if they show up, set a breakpoint and use the 3d view debugger to see if your nav bar is hidden under something, try using a placeholder / dummy UIViewController to verify that your segue is correct.

**Comment by machive** [comment]
Thanks Eli, I appreciate the advice, sorry to sound impatient. ;) I wish I was on holiday.....

**Comment by jessesquires** [comment]
Thanks for the answer @eliburke ! Much appreciated! :christmas_tree: :smile:
