### ISSUE TITLE
How to center custom JSQMessageMedia in Swift?

### ISSUE THREAD

**Issue by MHX792** [jessesquires/JSQMessagesViewController#1521]
I am trying to add a system message to `JSQMessagesViewController`. I chose to implement it as a `JSQMessageMedia`. It is shown in the view, but I have difficulties to center it.

The system message class:

    class ChatSystemMessage: NSObject, JSQMessageMediaData {
    
    
    @objc func mediaView() -> UIView! {
        let mediaView = UIView()
        let label = UILabel(frame: CGRectMake(0, 0, 200, 21))
        label.center = mediaView.center
        label.textAlignment = NSTextAlignment.Center
        label.text = "I'am a test label"
        mediaView.addSubview(label)
        return mediaView
    }
    
    @objc func mediaViewDisplaySize() -> CGSize {
        let size = CGSizeMake(200, 21)
        return size
    }
    
    @objc func mediaPlaceholderView() -> UIView! {
        return nil
    }

    @objc func mediaHash() -> UInt {
        return UInt(self.hash)
    }
    }

This is how it looks:

[![enter image description here][1]][1]

How could I center the message in the `cellForItemAtIndexPath` method? I don't know how to access the programmitcally created `label` in the `mediaView`.

  [1]: http://i.stack.imgur.com/3tTDL.png

**Comment by eliburke** [comment]
You have two choices:
1) hack the autolayout constraints in your subclass's call to cellForItemAtIndexPath 
2) create a custom cell 
- subclass JSQMessagesCollectionViewCell (look at *Incoming and *Outgoing to see what you must customize)
- set up the xib file how you like with the messageBubbleContainer centered instead of pinned to the avatar view
- register the nib in viewDidLoad of your JSQMessagesViewController subclass
`    [self.collectionView registerNib:[JSQMessagesCollectionViewCellCentered nib] forCellWithReuseIdentifier:[JSQMessagesCollectionViewCellCentered cellReuseIdentifier]];`
- In cellForItemAtIndexPath, detect your system messages by whatever means, probably by looking at the type of message in your data set. Instantiate your cell instead of calling the super implementation
```
- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
{
    JSQMessagesCollectionViewCell * cell;
    JSQMessage *msg = // something to get your data object
    if (msg.isSystemMessage) {
        cell = [collectionView dequeueReusableCellWithReuseIdentifier:JSQMessagesCollectionViewCellCentered.cellReuseIdentifier forIndexPath:indexPath];
        cell.textView.text = @"this cell is centered";
        cell.backgroundColor = [UIColor lightGrayColor];
        cell.textView.textAlignment = NSTextAlignmentCenter;
        cell.textView.backgroundColor = [UIColor darkGrayColor];
    } else {
        cell = (JSQMessagesCollectionViewCell *)[super collectionView:collectionView cellForItemAtIndexPath:indexPath];
    }
    return cell;
}
```

Here's a quick and dirty example that replaces all of the demo messages with centered text. Note that the bubbles are all different sizes because the underlying mediaItem is being used to determine the bubble size. 
https://github.com/eliburke/JSQMessagesViewController/tree/center_cell
Here's the commit if you just want to see the changes: https://github.com/eliburke/JSQMessagesViewController/commit/ab9a154b5e54a6e784bd3410c4242883234720d7

**Comment by MHX792** [comment]
Thank you for your in-depth answer. I will look into it. Do you have any hints for possibility 1)? How do you access the auto layout constraints programmitcally?

**Comment by eliburke** [comment]
Constraints can be set programmatically between views, just make sure to clear the old ones first. Stackoverflow or Google can provide more info.

**Comment by jessesquires** [comment]
Thanks @eliburke ! :smile:
