### ISSUE TITLE
Line to mark new/unread messages

### ISSUE THREAD

**Issue by rosslebeau** [jessesquires/JSQMessagesViewController#1546]
I'm using this library in an app, and we want to add a "New Messages" line, something like Slack has. I know this library wants to mimic iOS Messages (which does not have this), but I think that since it is so widely-used and extensible, other developers may also want this feature.

I'm going to have to implement this either way, so I figured it would be cool to see if this is something you want in this project. If so, I'd appreciate a little direction on a preferred method to implement this, as I can think of a few ways of getting this in the collectionview. E.g. it could be a cell, a header (with "read" and "unread" sections), or a view that is inserted by the layout.

**Comment by jessesquires** [comment]
Thanks @rosslebeau ! :smile: 

I'm actually not sure if I'm familiar with what you're describing in Slack — can you post a screenshot?

**Comment by rosslebeau** [comment]
Sure, here's an example:

<img width="700" alt="screen shot 2016-04-13 at 21 17 40" src="https://cloud.githubusercontent.com/assets/1470871/14514287/42a1defa-01bd-11e6-8399-f4c500f0939a.png">

I find this very useful for chat threads which have important messages you don't want to miss (like for work, or in my case, medical correspondence).

**Comment by jessesquires** [comment]
Ahh I see. :+1: 

So, right now this isn't supported for one major reason:

The collectionView in JSQMessages is item-based, not section-based. That is, it is a single section with many items, rather than having 1 item per section with multiple sections.

If it were section-based, this would be trivial. You could implement your own supplementary footer view and return it. 

However, v8.0 of the library will address this, as it will be moving to a section-based layout.

As far as including something like this in the library, I think:

- JSQMessages shouldn't contain any logic around finding new/old messages. That's too client-specific.
- Thus, I think this view it a bit too client-specific.

The goal however would be to make this as easy as possible for clients to do, thus 8.0 :smile:

**Comment by rosslebeau** [comment]
Oh, I didn't think the library would handle any logic around finding the old/new ones. I figured there would be some kind of delegate call to ask for the index of the last-read message when reloading data.

Yeah, with sections this will be simple, and I'm glad you're going that way...unfortunately I'm not sure I can wait until 8.0 is released. I guess if it's not usable by the time I need this, I'll have to hack in my own thing in the meantime.

I'm closing this issue since this is basically in the roadmap already. Thanks!

**Comment by jessesquires** [comment]
Thanks @rosslebeau ! :smile: 

Sorry it's not ready yet! :sweat_smile: You can follow the progress on v8.0 here: https://github.com/jessesquires/JSQMessagesViewController/labels/new%20release%20roadmap

**Comment by sreeji44** [comment]
@rosslebeau  sorry for interacting inside this... but if you done new/unread message Line can you help me by posting some tips.. and code. hope you will done this..

**Comment by rosslebeau** [comment]
@sreeji44 I have not done it, as it hasn't come up on my roadmap yet and I'm hoping JSQMessages v8.0 will be done first 😄 right now it will likely be a decent amount of work for such a small feature. It should be easy in v8.0.

**Comment by sreeji44** [comment]
@rosslebeau :) thankz for the reply and i also need to find it quickly as possible for my mission..  JSQMessage v8.0 when will release that  version 😄
