### ISSUE TITLE
Contribution: swift demo chat functionality

### ISSUE THREAD

**Issue by GianniCarlo** [jessesquires/JSQMessagesViewController#1608]
## New issue checklist

- [X] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [X] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation:  💪😎👊
- [X] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.
## Contribution

Hi @jessesquires I was about to make a pull request with the Swift demo completely updated to match all the chat functionality that the demo in Objective C has.

The thing is, besides all the functionality in the `JSQMessagesViewController` subclass, I saw that the ViewController containing the list of conversations has been removed currently in the branch `develop`. I would argue that seeing that most messaging apps have a chat list, it might make sense to include it in the demo. **Disclaimer:** In my branch I tweaked that ViewController haha

Here is my branch if you, or any of the contributors can check it out: [swift-demo](https://github.com/GianniCarlo/JSQMessagesViewController/tree/swift-demo) (commits already squashed)

If you prefer I can leave only the `JSQMessagesViewController` subclass implementation (and those of `User` and `Conversation` which it depends upon).

Let me know what you think. Really excited about the [port](https://github.com/MessageKit/MessageKit) of this library to Swift!

**Comment by jessesquires** [comment]
Hey @GianniCarlo ! 😄 

I would definitely like for the 2 demo projects to be as similar/consistent as possible. Preferably staying closer to the existing ObjC demo (with the exception of adding a "chat list" -- which would be a nice addition to the ObjC demo).

For now, I've been accepting most of @MacMeDan's pull requests without too many changes requests so that we can move quickly, but it would be nice to take some refinement passes and get the 2 demo apps in the same state. You and @MacMeDan should coordinate here. 😊 

Also — for `v8.0` (#1216) I'm going to be tearing things up quite a bit, so there might be a lot of churn here. Be prepared for lots of rebases 😅

**Comment by MacMeDan** [comment]
Agreed @jessesquires and @GianniCarlo 👍🏼. 
I removed the chat list because it had a error and It was not actually doing anything but if there is value in it I can definitely add it back in. I just feared that it may confuse people more then it help.
I'll take a look at this pull request and see what you are up too. 
Definitely open to suggestions. I am just trying to get on par with the Object C version/ just trying to add answers to Stack Overflow Questions.

Always open too thoughts. 💯

**Comment by GianniCarlo** [comment]
Great! @MacMeDan I'll explain here my changes, let me know when you get the chance to check it out.

What I think we can do about the chat list, once we got the settings ViewController fleshed out in Swift, it might make sense to add it as another option in that list.

#### Chat List
What I tweaked there was to show the difference in the text preview between a chat of two people and a group chat. I also added the cases when the last message is a type of media (photo, audio, video, location). For the demo it's initialized with each of these two types of conversation.

#### User struct
- id -> `String`
- name -> `String`
- avatar -> `JSQMessagesAvatarImage`

Really simple structure, only change was the addition of avatar for the demo.

#### Conversation class
To avoid having a var `type` of conversation (i.e. group, one-to-one), we can consider the conversation to be a group if the members count of the conversation is `>2`. This will help so in the preview in the Chat List, we can prefix the preview message text with the name of the sender only when it's a group.

Nowadays the name of the conversation between two people is usually the name of the recipient, but for groups it's always another thing.
- id -> `String`
- name -> `String`
- members -> Array of struct `User` 
- messages -> Array of `JSQMessage`
- isGroup -> `Bool`
- getUser() -> struct `User`

#### Chat `JSQMessagesViewController` subclass
I transcribed the Objective C code into Swift, the functions are in the same order so as to try and keep the demos as similar as possible

## Things left to do (as far as I know)
- Decide whether or not to keep the chat list as an option in the list of the initial controller
- Add configuration settings and finish up the initial controller to look like the one in the demo of Objective C
- If it's decided we can keep the chat list, then implement the equivalent to the demo in Objective C

*Is there anything else I'm missing regarding the demos?*

I haven't done the rebase yet of my branch with the last two commits of `develop` which erases the chat list. I'll defer to you @MacMeDan to let me know which way I should proceed so I can do the rebase accordingly and do the pull request. Also let me know which of the things left to do that I listed isn't being developed on currently so I can go on and contribute some more 👍

**Comment by GianniCarlo** [comment]
btw `JSQAudioMediaItem` isn't implemented in 7.2.0 apparently. I had to change it to 7.3.0 to make it run

**Comment by MacMeDan** [comment]
Interesting I had no issue with 7.2 but ya I will take a look later. I do already have a pull request for adding avatars to the demo and displaying the senders name over the bubble.

**Comment by jessesquires** [comment]
Also, small PRs please 😊

**Comment by MacMeDan** [comment]
Yes little chunks is the way to go. Makes it easier to see issues and get your code reviewed faster and when the base changes there are less conflicts.

**Comment by GianniCarlo** [comment]
Agreed, I just got a little too excited when transcribing the objective c demo to swift. I'll close this issue and split my changes into various pull requests for you @MacMeDan to checkout 👍

**Comment by MacMeDan** [comment]
Ya so looking through your code there are a ton of great things the issue is that this pull request would take weeks of back and forth to get it in. I would take one feature at a time and create pull requests with just that feature. 

Also I think with each feature we should add a setting to turn them on and off. This way any code relating to the feature is easily discovered without having to comb the entire project. This is currently demonstrated in the addAvatars pull request. And modeled after the current documentation.

- [x] avatars being displayed 

- [x] tailed and tailless message bubbles.

 - [ ] I like what you have done with group chats. l and think that would be really cool to demonstrate

- [ ] also in the objective c version 

- [ ] Video Message support 

- [ ] Audio Message support 

- [ ] Images Message support 

- [ ] Location Message support 

- [ ] Simulate incoming message

- [ ]  Removing sender ID for multiple consecutive messages sent by the same person.

- [ ]  Incoming `...` Animation 

I will make an issue for each of these individually.

**Comment by GianniCarlo** [comment]
Great! I'll get right on them 👍

**Comment by jessesquires** [comment]
Hey @MacMeDan and @GianniCarlo 😄 

Thanks for taking on this work! I'm trying to keep issues organized and lean. Going through a bunch of stuff today, and closing things out.

Let's keep this issue open and use @MacMeDan's checklist above to track this work instead of individual issues. 👍 

Sorry for the churn! 😊

**Comment by jessesquires** [comment]
hey guys, heads up #1654 is probably going to break all your swift code 😅

**Comment by MacMeDan** [comment]
That's alright tomorrow after lunch I'll have a couple of hours so I'll get it working again. 🤓

**Comment by Lucashuang0802** [comment]
Hmm, just wondering which Swift version we should use now? are we still using 2.2 or 3.0?

**Comment by GianniCarlo** [comment]
We're still using 2.2, dunno if you want to help migrating it @Lucashuang0802 ? I would think it best to hold off until it's out of beta, but anyways we should ask @MacMeDan and @jessesquires what they think about this subject

**Comment by jessesquires** [comment]
Definitely need to stay on 2.2 for now. We can update to 3.0 in one sweep after the final release of Xcode 8.

**Comment by Lucashuang0802** [comment]
@MacMeDan Do you think you need to update your checklist based on this #1725? I will be working on the front page soon. 😃

**Comment by MacMeDan** [comment]
Ya @Lucashuang0802 I will update it. Awesome Job 🏋🏻

**Comment by Lucashuang0802** [comment]
@MacMeDan Thx. Just wondering what's left for this issue. Front page? Setting?

**Comment by MacMeDan** [comment]
@Lucashuang0802 This is what we have not finished so far. But That is definitely not all that we could add. 
- [ ]  Removing sender ID for multiple consecutive messages sent by the same person. 
- [ ]  Incoming `...` Animation 
- [ ] Add Group conversation example to the objectiveC example.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
