### ISSUE TITLE
LocationMediaItem displaying  empty bubble 

### ISSUE THREAD

**Issue by SagarVarmaD** [jessesquires/JSQMessagesViewController#1679]
Hi all, 
I am trying to implement Location media in  xamarin iOS , i have given CLLocations values(longitude and latitude )values to Locationitem  .
I have tried the following code,
	CLLocation cl = new CLLocation (17.3850,78.4867);
				var locationItem = new LocationMediaItem (cl);
				locationItem.AppliesMediaViewMaskAsOutgoing = true;
				var locationmessage = new JSQMessagesViewController.Message(SenderId, SenderDisplayName,msgDate, locationItem);
				messages.Add (locationmessage);
![simulator screen shot 20-jun-2016 5 27 48 pm](https://cloud.githubusercontent.com/assets/19423167/16193390/904b7902-370c-11e6-8b62-758d61dd7f9c.png)

**Comment by Lucashuang0802** [comment]
@SagarVarmaD I think you should look up methods like `- (void)finishReceivingMessage;` and `- (void)finishSendingMessage;`. I think your code is okay, you will need to tell `JSQMessageViewController` that you finish sending or receiving messages and it should update the UI. Otherwise, only the data model is updated. It's like when you are using `UITableView`, you will need to call `reloadData` to update the table view.

**Comment by Lucashuang0802** [comment]
@jessesquires Looks like `MKMapSnapshotter` does indeed return a valid snapshot, see the attachment. But the problem is still there, smell like a bug. I can investigate more later.

<img width="1440" alt="screen shot 2016-07-17 at 10 58 13 pm" src="https://cloud.githubusercontent.com/assets/3754490/16906806/1d8d2b7e-4c72-11e6-9342-e867db5721e5.png">

**Comment by Lucashuang0802** [comment]
@SagarVarmaD Hey, if you read the docs carefully, you will find out that it's actually not the correct method to use. See the description of 
```
/**
 *  Initializes and returns a location media item object having the given location.
 *
 *  @param location The location for the media item. This value may be `nil`.
 *
 *  @return An initialized `JSQLocationMediaItem`.
 *
 *  @discussion If the location data must be dowloaded from the network,
 *  you may initialize a `JSQLocationMediaItem` object with a `nil` location.
 *  Once the location data has been retrieved, you can then set the location property
 *  using `setLocation: withCompletionHandler:`
 */
- (instancetype)initWithLocation:(nullable CLLocation *)location;
```

You should use `- (void)setLocation:(nullable CLLocation *)location withCompletionHandler:(nullable JSQLocationMediaItemCompletionBlock)completion;`. 😃

**Comment by Lucashuang0802** [comment]
@jessesquires not a bug, sorry for that.

**Comment by jessesquires** [comment]
thanks @Lucashuang0802 ! 🎉

**Comment by bacancyhima** [comment]
JSQLocationMediaItem is setting location each time when collectionview reloads. so it returns empty bubble until location reloads. i don't want to reload other JSQLocationMediaItem while adding new item, anyone having solution for this?
