### ISSUE TITLE
Photo Message UI issue in messages

### ISSUE THREAD

**Issue by niteshtak** [jessesquires/JSQMessagesViewController#1700]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 
- iOS version(s): 9.0
- Devices/Simulators affected: Device
- Reproducible in the demo project? (Yes/No):  yes
- Related issues: 
![img_0508](https://cloud.githubusercontent.com/assets/8844612/16402955/411452ce-3d23-11e6-829d-9983c66f790d.PNG)

#### Expected behavior
I dont want the extra gap below photo message

> ...

#### Actual behavior
It gives me unnecessary space below image in chat
> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by eliburke** [comment]
@niteshtak It looks like you have created a custom photo object. Is this the case? 
From your screenshot I can guess at a couple of possibilities: 
1) there is an invisible chat bubble that did not render properly
2) you are returning a bad value from your subclass - (CGSize)mediaViewDisplaySize; or - (UIView*)mediaView;
3) you are trying to show an image with an aspect ratio that can't be masked properly

Since you indicated that you can reproduce this in the demo project, perhaps that would be the easiest way to show us your code. Fork the repository, create a branch that shows the bug, and then push it back to github and tell us know the URL.

**Comment by jessesquires** [comment]
(closing, but discussion can continue. @niteshtak  we typically close question and help issues early to keep the project organized and focus on actual bugs.)
