### ISSUE TITLE
How to change textView width size in the inputToolbar.

### ISSUE THREAD

**Issue by morugu** [jessesquires/JSQMessagesViewController#1704]
I tried this code but not change size.

```
self.inputToolbar.contentView.textView.frame = CGRectMake(0, 0, 100, 50);
```

**Comment by Lucashuang0802** [comment]
When you did it in `viewDidLoad` and `viewWillAppear`, it won't get affected because the view controller has not finished loading. If you put it to `viewDidAppear`, it will get changed. But rather, it's better to take a look at the `JSQMessagesToolbarContentView.h`, it has some properties for the customization that might be helpful. @jessesquires can you give some comments here as well or we can close it? 😄

**Comment by jessesquires** [comment]
Changing the frame like this will get overridden by the layout constraints in the toolbar.

The class isn't really designed to be changed like this.

**Comment by Lucashuang0802** [comment]
Please note, the reason is actually overriding. Not the one I said from the
comment. Thanks. @jessesquires
