### ISSUE TITLE
Implementing custom cells with text fields and buttons

### ISSUE THREAD

**Issue by utkbansal** [jessesquires/JSQMessagesViewController#1708]
### General information

- Library version(s): 7
- iOS version(s): 9.3

### Custom Cells

I have read all the previous questions that are marked with the similar tags, but no success. I went through the FAQ readme where I got to know that I will have to create my own cell subclasses. So I am trying to do that. 

I need very custom cells, and there will me may types of cells. Cells may even have forms embedded in them. How do I do this?

What I have tried is make my own custom cell xib and custom cell subclass. But i get the following error - 
`Could not cast value of type 'JSQMessagesCollectionViewCellOutgoing'  to 'chat.CustomOutgoingCell' `

My `CustomOutgoingCell` is subclassing `JSQMessagesCollectionViewCellOutgoing`, but i still cannot downcast it.

**Comment by nguyenpham** [comment]
Without your code I can guess you might miss some steps ;)

In my case, I did not create a xib for the whole cell but the content inside of the bubbles only. My custom message is written as a media one. But instead of returning normal mediaItem (JSQMediaItem), it returns my own subclass. The code looks like below:

`    class MyMediaItem : JSQMediaItem {

    init(myMessage: ChatMessage) { // do whatever to init data
        super.init()
    }
    override init(maskAsOutgoing: Bool) {
        super.init(maskAsOutgoing: maskAsOutgoing)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func mediaView() -> UIView! {
        let myView = do whatever to create your view
        return myView
    }

    override func mediaViewDisplaySize() -> CGSize {
        return CGSizeMake(290, 170)
    }
}


You may see that the function mediaView has just returned an UIView which you can create programmatically or load totally from xib. Similar to mediaViewDisplaySize(), just calculate and return what size you want.

Happy coding :)

**Comment by jessesquires** [comment]
Thanks @nguyenpham ! 😄

**Comment by MHX792** [comment]
Thanks @nguyenpham, but where do I need to register the nib? In the `mediaView()` method or in the `collectionView`?

**Comment by utkbansal** [comment]
@mhx792 This might help http://stackoverflow.com/questions/38371995/jsqmessagesviewcontroller-send-text-message-with-attached-images-file/38414345#38414345
