### ISSUE TITLE
Implement navigation bar in JSQMessagesViewController

### ISSUE THREAD

**Issue by askaale** [jessesquires/JSQMessagesViewController#1777]
Basically I have a chat view controller that obviously displays the chat between two users. However, I have not figured out how to set a navigation bar in the chat view controller. I have tried to set a navigation bar in the Storyboard (design), but when I build and run the app - it disappears. The class of my chat view controller is of type JSQMessagesViewController, but I am not sure this may cause the error? I have tried to create a navigation bar programmatically, but then the navigation bar overrides (hides) the message bubbles (the very top messages). And also, while doing this - the constraints were all messed up. Any ideas on how I would solve this problem? 

Any help is much appreciated.

Thanks in advance.

**Comment by eliburke** [comment]
@askaale When you say you "set a navigation bar in the Storyboard" -- did you embed your chat view in a Navigation Controller? Because if you just set the simulated metrics to show a view controller that won't do anything 😄 

There is nothing specific to JSQMessagesViewController that needs to be done to put it in a Navigation Controller or Tab controller. If you are setting it up correctly and it doesn't show the navi, something is wrong with your code. You could try using the Debug View Heirarchy to verify if the Navigation Bar is created but off screen. For the manually created bar, you should be able to fix it with autolayout constraints or by setting the view's edgesForExtendedLayout property.

**Comment by jessesquires** [comment]
@askaale - Continuing from what @eliburke said, all you need to do is make your chat view controller the root view controller of a navigation controller, then present the navigation controller.

```swift
let chat = ChatViewController()
let nav = UINavigationController(rootViewController: chat)
```
