### ISSUE TITLE
Best practices for image loading with placeholders?

### ISSUE THREAD

**Issue by patniemeyer** [jessesquires/JSQMessagesViewController#1801]
I have read the docs, forums, and the code but I do not see a way to work with the JSQ image data sources to update images in cells upon completion of their loading.  Given that the data sources are a nice abstraction that encapsulates the notion of a placeholder I assumed there must be some way to update the underlying cell image when the image data is ready, but I don't see it.  It is relatively straightforward to override the collectionview methods to grab the cells as they are created or prepared to be shown and fire off async updates to the images... but if one is to do that what is the purpose of the image sources?  I see people suggesting using reloadData() on the collectionView to refresh images, but that is a heavyweight operation not really intended for this sort of thing, right?  The docs say it "discards the dataSource and delegate data".

**Comment by Lucashuang0802** [comment]
Hi @patniemeyer, I think you can do it without configuring anything related **JSQMessages** library. The logic is pretty straight forward actually. You can subclass `UIImageView`. The logic is to put the placeholder in `init` method. You will also need to provide a method to let your custom `UIImageView` class to handle downloading image to replace. When the image is downloaded, you just need to replace the placeholder with your downloaded image. There is actually nothing to deal with how you implement the `dataSource:` method, you can just need to fire it up from there.

Actually, `SDWebImage` did actually provide you an API to do it. You can check this out: https://github.com/rs/SDWebImage#using-uiimageviewwebcache-category-with-uitableview

**Comment by patniemeyer** [comment]
Hi, thanks but that that is exactly the problem - Because JSQMessages adds their own layer of indirection (e.g. JSQMessageAvatarImageDataSource) you *cannot* easily swap in your own image or use a third party API because you have no access to the UIImageView holder.  If JSQImages simply asked you for an image view you could at that time fire off an async update that later replaces the image as you suggest (or use SDWebImage's extension).  However what it does is ask you for a data source holder with an image... and updating that data source image has no effect.

Now of course you can override the collection methods to get called back when *cells* are used and you can delve into their view structure by casting and replace the JSQ MediaView or image, but it feels like I am missing some more obvious way to use the existing API.

For example - NYTPhotoViewer has a similar abstraction where you set an image and placeholder image on a NYTPhoto data source but in that case the controller provides a method to say: "Ok, update that image" and it re-checks the data source and chooses the real image if the placeholder is no longer needed.  I assume JSQMessages is heading in that direction and just hasn't completed that part of the API yet...  

If I am getting any of the above wrong please correct me.  Thanks.

**Comment by jessesquires** [comment]
Hey @patniemeyer ! 😄 

The goal behind the current API was to keep `JSQMVC` as "agnostic" as possible when comes to async image loading — that is, not enforce any kind of specific paradigm or external dependency like `SDWebImage`. More directly: there is intentionally **no networking** in `JSQMVC`.

`JSQMessageAvatarImageDataSource` should allow you to manage this however you want. Since this is a protocol, it can be any object. The library provides some default behavior here, but I imagine most clients would provide something specific to their use case. How and when requests are initiated is left entirely up to clients. 

----------------------------

> and updating that data source image has no effect.

Correct. This due to the above, and the library not knowing the specifics about clients. After you update your data source, you should know (or be able to derive) what has changed. At that point, you can tell the collectionView to reload specific index paths.

----------------------------

Here's a hypothetical flow for avatars:

Suppose you have some `ImageManager` class that conforms to `JSQMessageAvatarImageDataSource` and it keeps a dictionary of `[ indexPath : image ]`. 

The `JSQMessagesCollectionViewDataSource` protocol will ask for a data source *per* index path.

1. A photo message cell at `indexPath` is coming on screen
1. The `ImageManager` has a default `placeholder` ready to return for `avatarPlaceholderImage`
1. The `ImageManager` starts a network request for the image at `indexPath`
1. Request finishes. The `ImageManager` saves the image in the dictionary `[ indexPath : image ]`
1. The `ImageManager` tells the `collectionView` to reload the specific `indexPath`
1. When `JSQMVC` reloads a cell, it will first ask for the `avatarImage`, if `nil` it will ask for `avatarPlaceholderImage`

--------------------------

Having said that, this is a common point of confusion and I think we can improve the mechanisms/abstractions in the library to make this easier / more clear.

**Comment by patniemeyer** [comment]
@jessesquires Thanks for the explanation and for your work in general.  I agree that it's best if JSQMVC stays simple and does not get involved in the actual image loading.  But it would be helpful to clarify the workflow by providing JSQ Methods that support updating (re-checking) the image data source.  This could simply be a method on the controller that does what you describe above and reloads the appropriate index or perhaps be more efficiently implemented by having the data source prompt the cell to re-evaluate it and swap in the image for the placeholder when it is ready.  I must admit that I originally assumed that the image setter on the data source would trigger this kind of update and I think making that happen would be the most intuitive approach.  Alternately if the data source accepted a UIImageView instead of an Image the user could do what they wanted with it as @Lucashuang0802 mentioned.

Perhaps I can be of help and submit some code for this if you decide on an approach that you like.

**Comment by jessesquires** [comment]
Thanks @patniemeyer !

Not quite ready for a PR. I'll need to think about this a bit more with the other `v8.0` refactoring that's happening — but we'll definitely see how we can improve this.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
