### ISSUE TITLE
Segue to JSQMessagesViewController is too slow

### ISSUE THREAD

**Issue by MHX792** [jessesquires/JSQMessagesViewController#1819]
Hi,
the segue to my ChatViewController which is of kind JSQMessagesViewController is unfortunately too slow. I use pagination, i.e. only load the latest 20 messages. Here is the call tree:

![screen shot 2016-09-07 at 15 03 30](https://cloud.githubusercontent.com/assets/12123471/18313033/dce92da2-750c-11e6-8334-aa7dcd3ed0fc.png)

I use custom cells, but with the default tailless compact cell it's the same. When there are only a few messages it's quite fast though.

**Comment by jessesquires** [comment]
Thanks @MHX792 ! :smile: 

This doesn't seem specific to the library. StackOverflow is a more appropriate place to ask this question. :blush:

I'm going to close this issue, but the community should feel free to continue the discussion here.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)

**Comment by zhouzhongguang** [comment]
@MHX792 Is this problem solved? I come across this issue too.

**Comment by mradzinski** [comment]
What about loading the messages in an async fashion way? I mean, if you load a full chat of 10000 messages then the segue will obviously be slow. I would recommend or loading let's say 10 messages and then loading the rest once the segue completes or loading the messages on viewDidAppear() instead of having them load during viewDidLoad() since the last gets invoked before the segue happens. This should prevent the segue to be slow due to the fact that no messages (or just a few of them) will be present by the time the it kicks in...

**Comment by jessesquires** [comment]
Thanks @mradzinski !
