### ISSUE TITLE
messages persistance

### ISSUE THREAD

**Issue by barylevy** [jessesquires/JSQMessagesViewController#1919]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

## What happened?
persist the user messages

**Comment by MacMeDan** [comment]
I don't think I understand. Could you please🙏🏻  elaborate and we will see if we can help?

**Comment by barylevy** [comment]
Hi
I need to persist the messages in the conversation/chat when it ended.
The persist supports photo/video/audio that attached from Documents Library

**Comment by MacMeDan** [comment]
Ya so the JSQ Library does not provide anything in this regard in an effort to make this library extensible so anyone can use any storage method they choose. So you will need to look into a data storage solution. Often there are tutorials that use firebase as their backend. That is what I use in my personal projects because it has great documentation and super easy to use. There is this one form the getting started page https://github.com/firebase/ios-swift-chat-example I don't know how updated it is but you should be able to learn about the data storage and put them together. You can also use other solutions, mostly you are just making the right calls to the api to save the message data when the send button is pressed and download all new messages when a new message is received you make a call to download them.

**Comment by MacMeDan** [comment]
I hope that helps if you have more questions don't be afraid to ask. also [stackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller+firebase) has a ton of resources about this. Good luck 👾

**Comment by jessesquires** [comment]
👍
