### ISSUE TITLE
CollectionView Lag

### ISSUE THREAD

**Issue by renshaw1** [jessesquires/JSQMessagesViewController#2003]
I'm noticing a pretty heavy lag while scrolling through the CollectionView. 
I'm using the library in a Swift project with a bridging header. 
I don't have any Autolayout issues and my cellForItemAtIndexPath-method is similar to the one in the Swift sample project from Github:

`override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let cell = super.collectionView(collectionView, cellForItemAt: indexPath) as! JSQMessagesCollectionViewCell
        let message = messages[indexPath.item]
        
        let user = senderId()
        if (message.senderId == user) {
            cell.textView?.textColor = UIColor.black.withAlphaComponent(0.8)
            cell.textView?.linkTextAttributes = [
                NSForegroundColorAttributeName: APP_COLOR,
                NSUnderlineStyleAttributeName: NSUnderlineStyle.styleSingle.rawValue
            ]
        } else {
            cell.textView?.textColor = UIColor.white
            cell.textView?.linkTextAttributes = [
                NSForegroundColorAttributeName: UIColor.white,
                NSUnderlineStyleAttributeName: NSUnderlineStyle.styleSingle.rawValue
            ]
        }
        
    
        return cell
    }`

Here is a short screen video from my physical device. I hope you can see the lag, but it's definitely unnaturally high:
http://sendvid.com/n4n9fmxl

Thank you in advance.

**Comment by apwelsh** [comment]
Apple ran into this problem early on in iOS and created a mechanism for addressing this isue.    Instead if rendering all your cells i to an array, you want to only store the information necessary for creating the cells.    
  

  
Then you will use the dequeue technique. The demo project does not account for use cases that contain hubdreds or thousands of rows, or it too would need to ise the dequeue    reusable cell system.
  

  
Have a look here for how to do this in swift:
  

  
https://thatthinginswift.com/table-data-sources/
  
  
  
        
  

  
  
>

**Comment by renshaw1** [comment]
Hi,
Yes, but the library already does use that in the JSQMessagesViewController class.

I tested it on the sample project from Github as well, there is also a lag while scrolling through the collectionview, especially with > 10 cells.
Any way to fix this?

**Comment by apwelsh** [comment]
The reason for the dequeque code is that constructing so many UI components on memory, is very memory, and resource, intensive.  Basically, every cell is processing in memory, even if not being shown on the screen.  To leverage this logic correctly, you must not store all the tableViewCells in a collection.  It is that collection, not the table view, that is the problem.  The table view is just the mechanism which exploits the issue.  This also helps considerably with cpu load, since you wont have cells that are not rendered on the screen trying to render their content in the background.  The CPU only works on rendering the visible cells at the tine they are being displayed.  If properly implemented, the lag goes away completely. 

Well, if you turn off the spring animation.  The springiness really slows down the screen when scrolling.  But in the video I dont see that being the case.
Also, is this only on the Computer's iPhone simulator?  Did you try running on your phone?  Some slower macs will be laggy in the iphone simulator.

**Comment by ferdinand95** [comment]
Springiness is disabled. As I wrote, I tested on my physical device (iPhone 6)

**Comment by apwelsh** [comment]
The code snippet you posted use an NSArray of tableView cells.
  

  
Can you share your function as it is now?
  
  

    

    
  

  
>

**Comment by ferdinand95** [comment]
You mean _messages_? That's an Array of JSQMessages. My method hasn't changed.

**Comment by renshaw1** [comment]
You mean _messages_? That's an Array of JSQMessages. My code hasn't changed, the code remains the same as above.

**Comment by apwelsh** [comment]
Yes, but just realized you aren't using MediaItems, just raw text. So, that wouldn't necessarily be the issue, since the raw JSQMessage is just a simple data class, whereas media items are UIView components, which are quite a bit heavier than the simple JSQMessage.  If you had more complex / custom cells, i would stick with this being an issue with the implementation of the cellForItemAtIndexPath, however, I will have to defer to the developers on this one.  I can tell you that in my chat window, I do not have this lagging issue.

**Comment by renshaw1** [comment]
Okay, thank you anyway apwelsh :)
Would be great if one of the developers could reply, maybe there is a solution for this.

**Comment by algrid** [comment]
@renshaw1 Did you try to use profiler to identify problematic code portion?

**Comment by renshaw1** [comment]
Thanks for your answer. The CPU usage while scrolling through the CollectionView is definitely higher than in other TableViews in my app (it's 20-30% while scrolling, and over 70% when the CollectionView is initially shown)
I'm not experienced with regards to performance-management. How can I identify what code portion is the cause for the spike? I only see the threads in Xcode and Instruments.
Is 20-30% CPU consumption while scrolling bad on an iPhone 6? 

Thank you so much :)

**Comment by yarodevuci** [comment]
@renshaw1 Use Slack Chat, much smoother

**Comment by algrid** [comment]
@renshaw1 hm... it's hard to tell what's causing this. In sample project the CPU usage is a bit higher when you enable 'springy bubbles'. It may have something to do with collectionViewLayout.
Btw, can you reproduce this in sample project (maybe with some minimal changes)?

**Comment by MarkusWu** [comment]
@renshaw1 Is this issue resolved yet? If not, try resizing your avatar images. Large size of avatar can def slow down the collectionview performance, esp when you have many messages.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
