### ISSUE TITLE
Scroll to last message when opening the view

### ISSUE THREAD

**Issue by chlebta** [jessesquires/JSQMessagesViewController#2040]
## General information

- `JSQMessagesViewController` version: latest 7.3.4
- iOS version: 10
- Devices/Simulators: 6 plus / 5s / simulators
- Reproducible in the demo project? (Yes/No):  No

## What happened?
I've added `  automaticallyScrollsToMostRecentMessage = true `  into `viewDidLoad` but my collection view is not scrolling to last message (the bottom one)

**Comment by acjh** [comment]
Workaround: https://github.com/jessesquires/JSQMessagesViewController/issues/780#issuecomment-77236733

**Comment by apwelsh** [comment]
I do this in viewWillAppear.  Did load is called after the init.  As such, you are not overriding this value, since it is being reset after to change the value.  By putting it in viewWillAppear, you are change the value after it was reset.

Another value I have used in the past is viewDidAppear, so that you can see it scroll all the way down, but this is not very efficient.  If I recall correctly, I beleive doing it this way required more work tonforxe it to scroll down, since at this point it was already rendered.

**Comment by chlebta** [comment]
Finally I'had to add `self.scrollToBottom(animated: true)` in the end of `getData()` method

**Comment by Lucashuang0802** [comment]
@chlebta looks like this issue has been fixed. 👍
