### ISSUE TITLE
Unit-testing

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#298]
- Add more unit tests in general.
- Add UI tests (using demo app?)

**Comment by jeffkibuule** [comment]
Hey Jesse, I found some time and started looking to see what areas could use more testing with OCMock. First super simple thing I found was to try and test `UIDevice (JSQMessages)` which had no tests for `jsq_isCurrentDeviceBeforeiOS8`. Turns out, trying to mock systemVersion in a class category from a singleton is a lot harder than it initially looks. I've tried a few different approaches but keep coming up empty. I'll move onto something else to test later tonight.

**Comment by jeffkibuule** [comment]
@jessesquires

I have a better handle on writing tests now, so which behaviors would you like me to look at?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
