### ISSUE TITLE
Implement a lighter view controller

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#453]
Break up dataSources and delegates: 
1. messagesDataSource (JSQ-specific)
2. dataSource (collection view API)
3. messagesLayoutDelegate (JSQ-specific)
4. delegate (collection view API)
5. Editing delegate (actions: shouldCopy, didCopy, shouldDelete, didDelete)
- [ ] **Make these dataSources and delegates separate objects.**
- [ ] Introduce a cell factory to remove cell configuration into its own class

~~Also, fix remaining issues from #828, namely:~~ (See #920)

http://www.objc.io/issue-1/lighter-view-controllers.html

**Comment by erysaj** [comment]
Hi @jessesquires 
[Long ago[(https://github.com/jessesquires/JSQMessagesViewController/issues/319#issuecomment-44308954) I promised to present my vision on this topic
Back then I made a lot of changes for the project I develop, but unfortunately did not have time to update the demo accordingly for "presentation".
Recently I started moving changes related to lighter view controllers and fully custom cell classes on top of 7.0.0, so I suggest you take a look at the dedicated branch in [my repo](https://github.com/erysaj/JSQMessagesViewController/tree/dev-lighter-view-controllers)
The main challenges in adopting the approach from the original article were
* support for different cell types
* non-constant cell height; also size computations depend on cell type / displayed data so it makes
sense to move that code out of shared components.

Originally I tried to extend data source object with more block-based APIs, but
it turned out to be not really convenient (view controller was still cluttered with cell-specific code,
although wrapped in blocks), so I came up with a different solution.
It feels somewhat unusual even for me, but does its job in separating code.

Provided changes from the branch I've been able to use completely custom cells (no relation to `JSQMessagesCollectionViewCell`) with only one reservation - menu support delegate methods rely on internal cell structure and get in the way, so I commented them when integrating.

**Comment by erysaj** [comment]
@jessesquires don't mean to bug you, but I'm not sure if you noticed my last comment

**Comment by jessesquires** [comment]
Thanks @erysaj ! I'll look as soon as I can. :+1:

**Comment by andrew804** [comment]
Is there any news on sorting out the compiler warning -

/Pods/JSQMessagesViewController/JSQMessagesViewController/Layout/JSQMessagesCollectionViewFlowLayout.h:59:60: Property type 'JSQMessagesCollectionView *' is incompatible with type 'UICollectionView *' inherited from 'UICollectionViewLayout'

**Comment by jrmgx** [comment]
Please separated DataSource and Delegate :) :+1:

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
