### ISSUE TITLE
Black tint on navigation toolbar when pushing a new view controller from JSQMessagesViewController subclass

### ISSUE THREAD

**Issue by kartikthapar** [jessesquires/JSQMessagesViewController#528]
In the demo, simply add a new bar button item on the JSQDemoViewController storyboard view controller and push a new view controller from it. While pushing (and dismissing), there appears to be a temporary black tint/shadow on the top right corner.

This appears in both the simulator as well as on the device.

Weird thing — when I click on 'Modal View Storyboard' and return; and repeat the above experiment, no black tint is visible on the toolbar.

**Comment by BobDG** [comment]
Hi, for people still struggling with this issue I found the solution here:
http://stackoverflow.com/questions/22516046/ios7-strange-animation-when-using-hidesbottombarwhenpushed

The solution is either to
- Set your application window's backgroundColor to white (instead of default black)
OR 
- instead of hiesBottomBarWhenPushed use self.tabBarController.tabBar.hidden=YES in the second viewcontroller

The first one is better animation-wise and works perfectly here!

**Comment by jessesquires** [comment]
thanks @BobDG ! :+1:

**Comment by LevineKwok** [comment]
@BobDG The first one is worked !!! Thanks !!!
