### ISSUE TITLE
Layout bug on iPad when contained in split view controller

### ISSUE THREAD

**Issue by LeoNatan** [jessesquires/JSQMessagesViewController#533]
![ios simulator screen shot 7 oct 2014 11 57 20](https://cloud.githubusercontent.com/assets/2270433/4539738/34e04562-4e00-11e4-9c34-7cccd38e7ce3.png)

Something definitely changed between previous version and 6.0 beta regarding layout. This issue does not exist in previous version or iPhone. Rotating iPad fixes the issue temporarily until a new controller is used.

**Comment by proxxon-re** [comment]
I am using iOS8 with the current version of JSQMessagesViewController and the problem seems to appear again using a SplitViewController. The problem is here in JSQMessagesCollectionViewFlowLayout.m
- (CGFloat)itemWidth
{
return CGRectGetWidth(self.collectionView.frame) - self.sectionInset.left - self.sectionInset.right; 
}

self.collectionView.frame returns 320.0 an 703.5 during calculation of bubble sizes

Any idea how to fix it?
