### ISSUE TITLE
Scrolling does hide input and send button partially 

### ISSUE THREAD

**Issue by paatz04** [jessesquires/JSQMessagesViewController#666]
Hello,

since iOS 8.1.1 the input field and the send button get hidden after i scroll up having the keyboard open.
Do you have any idea what it might be or what I could do? Is this known bug?
I'm using the latest version of pod.. (Not the development branch)
Thank you very much

![img_6325](https://cloud.githubusercontent.com/assets/8363908/5327571/9f46ffc0-7d55-11e4-8225-cb5005b74a7a.PNG)

**Comment by jessesquires** [comment]
Hey @paatz04 - I noticed this behavior tonight, though not as you describe it.

My findings:

1. begin dragging toolbar
2. drag up and down rapidly
3. animations get glitchy, toolbar sometimes partially/completely hides behind keyboard (as pictured above)

**Comment by anilanar** [comment]
@jessesquires I'm working on replacing current implementation with `inputAccessoryView`. As of now, It works great for iOS7 and there is a minor animation curve difference between keyboard animation and scroll view animation (setting both insets and content offset). So I guess it will solve this bug. What do you say?

**Comment by jessesquires** [comment]
@anilanar - I'd love to see it!

**Comment by anilanar** [comment]
@jessesquires Currently I've accomplished docking a toolbar with a growing `UITextView` on top of the keyboard using `inputAccessoryView` and `UIScrollViewKeyboardDismissModeInteractive` for a typical `UICollectionView` without using a pan gesture recognizer, handling all discrepancies between iOS7 and iOS8, orientations and hardware keyboard.

I assume that it will be very easy to integrate it with `JSQMessagesViewController`, probably fixing #763, #558, #405 and many others related to keyboard frame change animations. I'm working on it so I'll let you know soon.

**Comment by anilanar** [comment]
@jessesquires I have integrated it with `JSQMessagesViewController`. However, there are a few restrictions:

- A height constraint must be used for input toolbar for iOS 8 because superview of `inputAccessoryView` (some private API class) uses AutoLayout and modifying the frame manually breaks things. Currently there is a height constraint already so I guess this is OK.

- Input toolbar is an `inputAccessoryView` of the collection view. For input toolbar to be visible, either the collection view or a subview of input toolbar must be the first responder. For example, using an `UIActionSheet` breaks this mechanism as it steals first responder status from them. This can be circumvented by using a custom `UIActionSheet`. I don't know what other cases can be a problem with this restriction.

- For iOS7: when a navigation controller is used and if another view controller is pushed and popped back, input text view will resign first responder status even if it was the first responder pushing another view controller.

I will try to publish a proof of concept in a few days.

**Comment by anilanar** [comment]
Here we go: https://github.com/anilanar/MessagesTableViewController/commit/979e996cd7d2138f1101ded3322ca25f9c3c5495

I didn't test it for iOS7.0. It seems to work OK with 7.1 and 8.1. 
It probably won't look good with iPad undocking and keyboard splitting in its current state but they are fixable. 

Just check the new keyboard controller and see how unpredictable iOS keyboard events are (hardware keyboard, rotations, input view accessory size changes etc.). There are some basic rules but for some cases, they are broken beyond imagination.

**Comment by anilanar** [comment]
@jessesquires Have you checked it yet? If you like the idea of `inputAccessoryView` way, I can work on it as I have free time nowadays.

**Comment by jessesquires** [comment]
@anilanar - not yet, but I'll try to get to it this week!

**Comment by jardamach** [comment]
@jessesquires: Hi Jesse, I noticed that you have UIScrollViewKeyboardDismissModeNone in JSQMessagesCollectionView. Isn't it redundant and probably also cause of this keyboard troubles? - you manage keyboard frame in your custom JSQMessagesKeyboardController. I tried removing it in your demo and it works like a charm.

**Comment by jessesquires** [comment]
@jardamach - awesome! thanks. 

sounds like `UIScrollViewKeyboardDismissModeInteractive` was a mistake. does removing that resolve this issue?

**Comment by jardamach** [comment]
@jessesquires I believe so. And also I think that in observeValueForKeyPath inside JSQMessagesKeyboardController you should convert newKeyboardFrame to contextView coordinate system -> 

   CGRect keyboardEndFrameConverted = [self.contextView convertRect:newKeyboardFrame fromView:nil];

and send keyboardEndFrameConverted instead of newKeyboardFrame - like this:
[self jsq_notifyKeyboardFrameNotificationForFrame:keyboardEndFrameConverted];

Because for example in jsq_handleKeyboardNotification you are converting this rect but inside observeValueForKeyPath you don't -> There may be layout problems if the contextRect has origin different than CGPointZero.

**Comment by jessesquires** [comment]
Thanks @jardamach ! Super helpful info. 

Much of this changed (broke) going from iOS 7 to iOS 8

**Comment by jessesquires** [comment]
fixed in 97bfef2

still investing @jardamach's comment above on frames

**Comment by erysaj** [comment]
Updating `-[JSQMessagesKeyboardController observeValueForKeyPath:...]`
breaks iOS7
The steps to reproduce are as follows (iPad iOS 7.1.2):
* enable "load extra messages" option in settings
* go to chat
* rotate to landscape
* tap on input 
* slowly drag collection view until input text view disappears
* release your finger, keyboard should jump back to original position

**Result**: keyboard is presented, but input toolbar is not visible
I believe I've seen this scenario in some issue's discussion, but can't find which one

On iOS8 things are even worse in this scenario:
during slow dragging keyboard with toolbar can suddenly jump to half-visible position and
remain at it until input loses focus.

Reverting mentioned change fixes iOS7 case, but nothing changes on iOS8.
I'm investigating iOS8 case further

**Comment by erysaj** [comment]
The frame is observed on the `keyboardView` so the rect is in its superview coordinate space (unlike frames from keyboard notifications which are in window's),
so I suppose it'd be correct to replace 
```objective-c
CGRect keyboardEndFrameConverted = [self.contextView convertRect:newKeyboardFrame fromView:nil];
```
with this:
```objective-c
CGRect keyboardEndFrameConverted = [self.contextView convertRect:newKeyboardFrame fromView:self.keyboardView.superview];
```

**Comment by jardamach** [comment]
Arh, didn't notice this problem happening on iPad iOS7.1.2. Sorry about that. @erysaj's solution fixes the problem. 

however, I was unable to reproduce iOS8 scenario. Everything worked fine on the current version. I just experienced some issues with media cell.

**Comment by erysaj** [comment]
I happened to check on a device with pretty old version - 8.0 
as a result `+[UIDevice jsq_isCurrentDeviceBeforeiOS8]` worked incorrectly - it compares
current version to `@"8.0.0"` so the window height was determined as if it is iOS7 and caused a mess.

**Comment by jessesquires** [comment]
thanks @erysaj and @jardamach ! :+1: 

re-opened this issue and tagged it for the 7.0.1 milestone
