### ISSUE TITLE
ViewController sometimes empty

### ISSUE THREAD

**Issue by pflenker** [jessesquires/JSQMessagesViewController#715]
Hi there,

I have one of those annoying bugs that is very hard to track down, so I'd like to ask here if anyone else has been seeing this issue or if it might be part of my code.

Every once in a while,but very rarely,  the JSQMessagesViewController displays "nothing", meaning: The bottom bar is there, I can enter and send text and everything, but I see no avatars, no message bubbles, no toplabel, no bottom label, nothing. I can scroll around a seemingly empty scroll view, I can see the scroll bars and from that I can see that it has the right height. Nothing helps to recover from that state, including sending and receiving messages, calling `self.collectionView.reloadData()` or rotating the screen. Restarting the app always works, even if the loaded objects themselves do not change in the meantime.

I am seeing this on my iPhone 6 with  version 6.1.1 and a swift subclass of JSQMessagesViewController.
Since I have no clue whatsoever on reproducing this issue, and sometimes it occurs when I don't have a debug session, I am having a hard time figuring this one out. 

Is anybody else seeing this? Do you have any ideas on how to fix this?

Thanks and best regards,
Philipp

**Comment by jessesquires** [comment]
Hey @pflenker - are you installing via Cocoapods 0.36 pre-release?

**Comment by pflenker** [comment]
Hey @jessesquires , nope, I am using 0.35.0 .

**Comment by lgjenero** [comment]
Hey @pflenker & @jessesquires I ran into a similar if not same problem. Sometimes, but only on when I would open the chat view for the first time, the view would appear blank but scrollable. Also delegate methods for the chat view were triggered. I noticed that if I limited the number of messages to a small number (all messages could be shown on the screen) the issues went away. Furthermore I moved my data loading code from viewDidLoad to viewWillAppear and that also seems to have helped with the issue.
Hope this helps,
Luko

**Comment by jessesquires** [comment]
Thanks @lgjenero!

@pflenker - did this solution work for you?

Also, are you still seeing this on the latest build?

Since you are using Swift, maybe resources weren't loading for some reason, which [6.1.2](https://github.com/jessesquires/JSQMessagesViewController/releases/tag/6.1.2) should have fixed

**Comment by kittany13** [comment]
hi 
I ran into a similar problem too, and i solved it by refreshing the collectionView after completing your data loading:
.. for example after getting answer from server.
since you got your data you will have to load the self.data - array.
  self.data = [[ModelData alloc] initWithArray:dataArray];

here comes the part when you add this row:
[self.collectionView reloadData];

**Comment by tjwudi** [comment]
Also having this issue with latest build. Neither `reloadData` nor moving data initialization from `viewDidLoad` to `viewWillAppear` works.

**Comment by tjwudi** [comment]
More context: I am having this issue when subclassing `JSQMessagesViewController` and override   the nib file. I copied **JSQMessagesViewController.xib** to the main bundle and renamed it to **XXMessagesViewController.xib**, changed the owner to my new subclass `XXMessagesViewController`.

Anything I am missing here to overrider `+(nib:)`? @jessesquires 

My XXMessagesViewController class:

```
#import "XXMessagesViewController.h"

@interface XXMessagesViewController ()

@end

@implementation XXMessagesViewController

+ (UINib *)nib
{
    return [UINib nibWithNibName:NSStringFromClass([NicieMessagesViewController class])
                          bundle:[NSBundle mainBundle]];
}

@end
```

**Comment by tjwudi** [comment]
I just figured out this is because of XCode :(

I am currently using XCode 10. After copying **JSQMessagesViewController.xib** from the packages bundle to main bundle and changing the file's owner to my own subclass `XXMessagesViewController`, XCode magically changes some fields that have nothing to do file's owner, hence the issue.

**Comment by brbgyn** [comment]
I have the exactly same problem. Its been in my app for more than a year.

Anyone could solve this ?
