### ISSUE TITLE
Fast device rotation vertical-horizontal-vertical:  the framework doesn't realign message bubbles correctly

### ISSUE THREAD

**Issue by TediumRemedy** [jessesquires/JSQMessagesViewController#717]
If you position a phone vertically, rotate it horizontally and as soon as the screen rotates, rotate it back vertically,  the bubbles positions will get messed up (the bubbles will be located as if there still were a horizontal orientation).
The same with horizontal-vertical-horizontal rotation.

Also there's a problem with the "input toolbar" still remaining on top after the keyboard has already hidden. It can be reproduced the same way - you need to rotate quickly horizontally and back vertically with the keyboard on.

**Comment by jessesquires** [comment]
Thanks @TediumRemedy !

I was able to reproduce this but not very frequently. 

I'm going to close as *will not fix* for now, because I think this is an extreme edge case, and doubt this will come up in "real world usage". However, it's still good to know about.

Further, the layout invalidation that's happening right now during rotation is about all we can do to fix something like this. As far as I know, there's no good way to figure out if the user has rotated her device this quickly back-and-forth. (So I'm not 100% what the fix would be, if any.)

If it becomes a larger/more prominent issue, I'll be happy to re-open.

**Comment by TediumRemedy** [comment]
@jessesquires 

For me it happened quite often (when i put the device on a table, it may rotate back and forth several times), so what i did was removing "extend edges" from the view controller in interface builder and adding the code:

- (void)viewWillLayoutSubviews {
    NSLog(@"viewWillLayoutSubviews");
    [self.collectionView.collectionViewLayout performSelector:@selector(jsq_resetLayout)];
    [self.collectionView.collectionViewLayout invalidateLayoutWithContext:[JSQMessagesCollectionViewFlowLayoutInvalidationContext context]];
}

to the view controller, which seems to have fixed the problem. It also made the warnings in #642 go away.
The only problem is that this method is invoked too often (may impact performance?).

Source: http://stackoverflow.com/questions/16013209/uicollectionview-layout-issue

**Comment by jessesquires** [comment]
Interesting!

Yes — I would not recommend overriding `viewWillLayoutSubviews` with this code.

Also, `jsq_*` methods are private methods. Use at your own risk! :smile:
