### ISSUE TITLE
Insert a view to the collectionView?

### ISSUE THREAD

**Issue by TediumRemedy** [jessesquires/JSQMessagesViewController#720]
Hi, I am trying to insert a custom view to the bottom of JSQMessagesViewController's collectionView, as it was a message. After it there will be no more messages added and the typing indicator won't be shown (I am inserting it in the end of a conversation). 
Here's what I am doing:

    NSArray *cells = self.collectionView.visibleCells;
    NSLog(@"%@", cells);
    UICollectionViewCell *lastCell = [cells lastObject];
    CGFloat y = 0;
    if(lastCell) {
        y = lastCell.frame.origin.y+lastCell.frame.size.height;
    }
    self.customViewToInsert.frame = CGRectMake(0, y, self.collectionView.frame.size.width, 45);
    [self.collectionView addSubview:self.adView];
    [self.collectionView setNeedsDisplay];

The problem is that self.collectionView.visibleCells always returns an empty array even if there are messages. 
Could you please suggest how to add a view correctly?
Thank you

**Comment by jessesquires** [comment]
Hey @TediumRemedy, a few tips

1. I'm pretty sure that `visibleCells` is nondeterministic. It does not guarantee order, so `lastObject` is not going to work.
* You should use the [CGGeometry](http://nshipster.com/cggeometry/) functions instead of accessing frame properties directly. (e.g., `CGRectGetHeight()` instead of `frame.size.height`)
* It's a bad idea to add subviews directly to a collection view. You will have issues with this. This is what cells, supplemental views, and accessory views are for.

Regarding `visibleCells` being empty, there's nothing specific to this library that should cause that. If you are calling this while the view is appearing/disappearing/updating then that might be your problem. Otherwise, this is probably a question for StackOverflow.

**Comment by TediumRemedy** [comment]
Thanks @jessesquires
