### ISSUE TITLE
Move strings to resource bundle (Add localization subspec)

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#784]
See #778

**Comment by benmagos** [comment]
I believe the main purpose of this is to prevent an App with JSQMessages installed to list all of JSQ's supported languages in the App Store, correct? Would it not be more effective to include all the localization **.lproj* files within the JSQMessagesAssets.bundle rather than just in the Resources folder? I *believe* that would prevent iTunesConnect from including the .lproj files in any submitted applications, though I could be mistaken.

If this is not the case, @jessesquires, how would you want this to be implemented? A separate subspec for each language? So people could choose specific languages they want to include in their Podfile?

For example, for an app that only supports English and German:
```
pod 'JSQMessagesViewController/en'
pod 'JSQMessagesViewController/de'
```
as opposed to including all with:
`pod 'JSQMessagesViewController'`

Let me know!

**Comment by jessesquires** [comment]
@benmagos - correct. 

Either solution sounds good! :+1: (assuming the asset bundle suggestion behaves like you think it does)

If you want to submit a PR, please also add a new "**Localization**" bullet that explains these changes to the "Getting Started" section in the `README`.

**Comment by benmagos** [comment]
Thank you. I'm happy to include separate subspecs for each language, but think it may be better practice to include the Strings within the JSQMessagesAssets.bundle file. But AFAIK, we have no way of knowing if it behaves the way I think it does until... the next time I or someone else submits a version to the App Store.

I believe this may be the issue described here:
https://github.com/CocoaPods/CocoaPods/issues/1930

Which would lead me to believe that simply moving the files into the .bundle would be the way to go.

An added bit of support for this behavior would be that I also use https://github.com/MatthewYork/DateTools, but its Localizations are within DateTools.bundle, and my app on the App Store only includes the ones that JSQMessages supports, and not the additional ones that DateTools supports.

I will go ahead and submit a PR of simply moving the Strings into the .bundle, and if you decide you also want or would rather the subspecs, I could do that instead.

**Comment by benmagos** [comment]
For the three localized strings, what would the best way be of accessing the localized string table within the bundle be:
```
[self.loadButton setTitle:NSLocalizedStringFromTableInBundle(@"Load Earlier Messages", @"JSQMessages", [NSBundle bundleWithPath:[[[NSBundle mainBundle] bundlePath] stringByAppendingPathComponent: @"/Assets/JSQMessagesAssets.bundle"]], @"Text for button to load previously sent messages")
```

Or do you have a different preference?
I had submitted a PR and realized I didn't change how the strings would actually reference the new location of the JSQMessages.strings file so I closed it. :smile: I'm a bit new at open source contributing, so I'm having a hard time testing since trying to run the JSQMessages.xcworkspace isn't working for me.

**Comment by jessesquires** [comment]
Thanks for all the information @benmagos ! Nice work :+1: 

Sounds like https://github.com/CocoaPods/CocoaPods/issues/1930 is the solution, I need to switch the spec over to `s.resource_bundle`.

This is actually going to require some more substantial work, so I'll take it from here.

>I'm a bit new at open source contributing

Contributing all of this time and information is just as important a contribution as code — if not **more**.

>trying to run the JSQMessages.xcworkspace isn't working for me.

After you clone the repo, you'll need to run `pod install`

**Comment by benmagos** [comment]
Thanks for the tip and encouragement @jessesquires, let me know where else I can help, if I don't find a reasonably attackable issue before then :smile:

**Comment by jessesquires** [comment]
:+1: 

I try to keep issues as organized as possible. Anything labeled as "bug" is fair game!

There's also a "needs investigation" for things I haven't verified. If you can reproduce those issues, and note your findings, that's also super helpful!

**Comment by jessesquires** [comment]
For anyone wishing to remove localizations, you can use the following method:
https://github.com/mattt/FormatterKit#removing-unused-localizations

**Comment by jessesquires** [comment]
Updated issue to only deal with localization. 

Resource bundle work deferred to #865
