### ISSUE TITLE
is it possible to return a UIViewController as a media item?

### ISSUE THREAD

**Issue by ryanmeador** [jessesquires/JSQMessagesViewController#801]
I'm trying to make a video player inside a message cell.  That is, I literally want to play my video inline in the chat, bounded by the nice bubble shape of a message.  I got it working with the MPMoviePlayerController, embedding it in a view and returning it from my JSQVideoMediaItem like so:

```
- (UIView *)mediaView
{
    if (self.fileURL == nil || !self.isReadyToPlay) {
        return nil;
    }
    
    if (self.cachedVideoView) {
        return self.cachedVideoView;
    }
    
    CGSize size = [self mediaViewDisplaySize];
    
    UIView *videoView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, size.width, size.height)];
    
    videoView.contentMode = UIViewContentModeCenter;
    videoView.clipsToBounds = YES;
    [JSQMessagesMediaViewBubbleImageMasker applyBubbleImageMaskToMediaView:videoView isOutgoing:self.appliesMediaViewMaskAsOutgoing];
    
    self.moviePlayer = [[MPMoviePlayerController alloc] initWithContentURL:self.fileURL];
    [self.moviePlayer.view setFrame:videoView.bounds];
    [videoView addSubview:self.moviePlayer.view];

    self.moviePlayer.shouldAutoplay = YES;
    self.moviePlayer.repeatMode = MPMovieRepeatModeOne;
    [self.moviePlayer prepareToPlay];
    [self.moviePlayer play];

    self.cachedVideoView = videoView;
    
    return self.cachedVideoView;
}
```

But MPMoviePlayerController lacks much of the functionality I need, so I'm attempting to use [PBJVideoPlayer](https://github.com/piemonte/PBJVideoPlayer) and/or roll my own from AVPlayer directly.  Both of these latter approaches seem to require adding the video player as a child view controller, but I don't have access to the parent view controller inside the `mediaView` function.  Is it possible to somehow return a UIViewController instead of a UIView?  How would you recommend I tackle this?

**Comment by anilanar** [comment]
I don't think `UICollectionView` is well suited for that. However for your problem, you can do the following:
- Create a custom `UIView`
- Have a property of type `PBJVideoPlayerController` inside it
- Init it as usual, set your custom view as delegate, add `videoPlayerController.view` as a subview
-set your videoPath (or you can do that by implementing `- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath`)

**Comment by anilanar** [comment]
I don't think `UICollectionView` is well suited for that. However for your problem, you can do the following:
- Create a custom `UIView`
- Have a property of type `PBJVideoPlayerController` inside it
- Init it as usual, set your custom view as delegate, add `videoPlayerController.view` as a subview
 - Either set your videoPath here
 - Or implement `- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath` and change it there.

This will just work. When you scroll away from a player, its view and controller, everything will be dealloc'ed. What would have been better is if you reused your player views. For that, you have to go up the hierarchy, implement your own cell and override `prepareForReuse`, override `- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath` etc.

@jessesquires 
Maybe it is a good idea to let custom views have their own `prepareForReuse` methods instead of nullifying them.

**Comment by ryanmeador** [comment]
Thanks for the info!  I've implemented a working solution based largely on your advice.  I have seen an occasional failure to draw the video, which is very intermittent, and I've even seen it a couple of times with photos (which I haven't modified, that's straight JSQPhotoMediaItem).  I wonder if there is some latent bug in the library that video triggers on rare occasions.  If I figure out what's going on, I'll file another issue for that.

Do you have a recommendation for stopping the video when it scrolls away?  I don't particularly care from a UI perspective because there's no audio, but it would be good to not consume the resources.

**Comment by anilanar** [comment]
I've seen also seen some images not being drawn when scrolled too fast? I'm not sure and don't know if there's an issue submitted about that.

To stop your videos, you should implement `
collectionView:didEndDisplayingCell:forItemAtIndexPath:` of `UICollectionViewDelegate`, find the cell with `collectionView:cellForItemAtIndexPath:`, access your custom media view (and thus the video controller) and call pause.

**Comment by ryanmeador** [comment]
Thanks, that's perfect.

**Comment by jessesquires** [comment]
thanks guys! great discussion here.

closing this as resolved. for any other potential bugs mentioned here, please open new issues. :+1:
