### ISSUE TITLE
JSQMessage isEqual returns false

### ISSUE THREAD

**Issue by csapinoso** [jessesquires/JSQMessagesViewController#858]
Hi @jessesquires ,

In my code I'm trying to detect if the incoming message is the same one as what I previously have sent so I don't display duplicate messages after sending one. I'm trying to use the isEqual method but it's always failing because of the date comparison. I'm comparing the original message stored in the datasource array and a copy of the same object deserialized from a json response. When I convert the two dates to string readable format they are exactly the same. I was wondering if this is a bug or I'm just not using the method correctly?

btw, awesome job on this library, I appreciate your work so much!

**Comment by jessesquires** [comment]
Thanks @csapinoso - This sounds like expected behavior.

>When I convert the two dates to string readable format they are exactly the same.

What does this mean? An ISO 8601 string (e.g., `2015-03-13T17:51:29+00:00`) or a human-readable string (e.g., `Today, 2:23pm`)?

Some of this depends are your architecture. Are you sending the timestamp to the server, or does it timestamp data for you? That would explain inconsistencies.

Alternatively, you can simply compare `senderId` and `text` content.
