### ISSUE TITLE
How can I add emotion in messages(not the emoji emotion inbuild in ios)?

### ISSUE THREAD

**Issue by ZsIsMe** [jessesquires/JSQMessagesViewController#863]
I want to add my own emotion in the message,how to do it?
Thanks!

**Comment by jessesquires** [comment]
@ZsIsMe - you could use the media messages interface for this. Otherwise, the library doesn't really support this.

**Comment by mohpor** [comment]
With all due respect, the library almost well supports it, but right not out of the box. I have implemented it successfully and it is working great!

I can provide a good tutorial if you want.

P.S.: I was going to talk about it in a new issue, but, take a look at this:
[WUEmoticonsKeyboard](https://github.com/YuAo/WUEmoticonsKeyboard)
it'll be great to add it to the library, and I know all about milestones and all :smile:

**Comment by jessesquires** [comment]
Awesome! Thanks @mohpor :+1: 

I don't think I'd want to add `WUEmoticonsKeyboard` as an explicit dependency, but if something needs changing to make it easier to integrate, let me know.

**Comment by ZsIsMe** [comment]
@mohpor thank you!
 If you can give me the tutorial,that's great!
I want to use this framework in my xmpp project, but the emotion in unicode is to ugly, i need to use mine.
Thanks!

**Comment by ZsIsMe** [comment]
@mohpor  
After I see the demo WUEmoticonsKeyboard, I don't know how to do yet.
I know I can send the smile face as [smile] in the string,just like "Hello![smile]"
but how can i make it become emotion in the string when others receive it in the cell?

**Comment by mohpor** [comment]
Here is a simple how-to:
(beware, you need to change this library to support it)

1- you need to change the way TextMessages works in `JSQMessageViewController` to use `NSAttributedString` instead of `NSString`. (don't forget to change the sizing methods too, plus there are Assertions related to Text property of TextView for each message)
2- You're gonna have to fish out all the texts you need to replace with your smilies. (it's harder than it sounds, but more on this later if you wanted to know)
3- replace all ranges you have found with instances of `NSTextAttachment` corresponding to your smiley image. e.g.: `NSTextAttachment *smileyAttachment=[[NSTextAttachment alloc] init];
smileyAttachment.image=*yourSmileyImage*;
...
` and create an `NSAttributedString` out of these attachments and replace them with your matched ranges
4- Set the text message text view's `attributedString` to the generated `NSAttributedString`

and that's basically it, but there is lot more you need to do, especially when it comes to sizing and other things.

Sorry for the brief tutorial, it really is out of scope of an issue on github!

**Comment by mohpor** [comment]
@jessesquires , thanks for your attention
It doesn't need anything changed to work with `WUEmotconsKeyboard` but we can facilitate developers' work to provide them with some data source and delegates to easily incorporate these two beautiful libraries, which are in my idea, essential libraries to develop a messaging app.

**Comment by ZsIsMe** [comment]
@mohpor I am trying，thx!!!!

**Comment by rkittinger** [comment]
@mohpor I have tried something similar to this in our app, but the emotion is not animating... any experience with this? Are your emotions animated? This would be a very important criteria and choosing this framework. Thanks.

**Comment by mohpor** [comment]
@rkittinger Unfortunately I have moved away from that project, but to help you get your answer, you should investigate IF `NSTextAttachment` accepts animated gifs (I guess they don't but I might be wrong).
http://stackoverflow.com/questions/29135232/animated-gif-inside-uitextview
http://stackoverflow.com/questions/29949348/animated-uiimage-in-uitextview-with-textkit

Hope this helps
Cheers,
M.

**Comment by rkittinger** [comment]
Thanks,

already looked at those links. Assuming the JSQMessagesViewController bubble views can be modified to use attributed strings like you said, I am trying to use bezier paths and embed the gif as a subview. Not just trying to position the text correctly.
Do you have the project/code where you changed the ‚strings‘ to ‚attributedstrings‘ ?

Thank you
Randy

**Comment by mohpor** [comment]
I'm afraid I don't have them.
It's nothing you can't do.
Just make a factory method to properly convert every text to attributes strings, change the setter methods, and change the sizing methods that use NSString sizes to attributed counterparts and you are done! I'm sure you can do it in under an hour ;)
Sorry I couldn't help more.

**Comment by eliburke** [comment]
I think that part of the roadmap for release 8 includes switching to attributed strings, right @jessesquires ? So @rkittinger if you are continuing to work on this, patches are welcome.

**Comment by jessesquires** [comment]
Thanks correct. For `v8.0` text messages will provide `NSAttributedString` instead of `NSString`

**Comment by rkittinger** [comment]
When is the planned release date? Would it be possible to attach animated gifs into the messages like Skype? Or does anyone know how Skype achieves this?
