### ISSUE TITLE
[Version 7.0.0] NSParameterAssert causes app to crash

### ISSUE THREAD

**Issue by Foriger** [jessesquires/JSQMessagesViewController#895]
Hi @jessesquires .

Small question about 7.0.0 changes.

I have an iPad version of my app, using UISplitViewController.
After update to 7.0.0, there is a crash with it. There are two newly added NSParameterAssert calls in viewWillAppear method of JSQMessageViewController: 

```
- (void)viewWillAppear:(BOOL)animated
{
   NSParameterAssert(self.senderId != nil);
   NSParameterAssert(self.senderDisplayName != nil);
 // more code ...
}
```
Thos crashes my app because collection view will be not loaded at all (I take senderId and senderDisplayName from Core Data model), because if there is no messages senderId and  senderDisplayName will be nil

What I've done is to add to my  viewDidLoad implementation default values of displayName and senderID like this:
```
-(void)viewDidLoad
{
  [super viewDidLoad];
  self.senderDisplayName = @"Banana";
  self.senderId = @"Monkey";
}
```
but still not sure, that this is good/ correct way to do it.

So my question is: why this asserts was added, and have I done fix correctly?

P.S Sorry if question is kind of silly, but I need to be sure :)

**Comment by jessesquires** [comment]
Hey @Foriger - prior to 7.0, the library provided default values for these 2 properties. This change was made because it didn't really make sense for the library to do this. 

There are no "good" default values here from the library's perspective, so it is now left up to the client. The asserts are there because it doesn't make sense to display this view without these 2 pieces of information.

Also, the previous default values resulted in **tons** of questions (#882, #695, and others) because people would forget to set these values.

So, yes. This is *almost* the correct solution. You shouldn't have to have default values (though it does fix the problem). The `senderId` and `senderDisplayName` refer to **the user who is currently using your app** — which is why these values should *never* be `nil`. You should always know who the current sender is, even if you are pushing an empty messages view.

**Comment by Foriger** [comment]
I understand.
Thanks @jessesquires
