### ISSUE TITLE
Disable chat orientation

### ISSUE THREAD

**Issue by carlos16196** [jessesquires/JSQMessagesViewController#926]
great control, really love it, although i have a really small concern:
i have been trying to disable orientation on chat page for days now. i tried shouldautorotate, willrotate, didrotate, preferedorientation, supportedorientation, and the only view i dont need to rotate still does.

where and how should i control this property?

**Comment by carlos16196** [comment]
well for future reference, i resolved this by making a category of UIViewController which overrides shouldautorotate, then imported the created category "UIViewController+Orientation.h" into the class (chatroom) that subclasses JSQMessagesViewController.

**Comment by jessesquires** [comment]
Hey @carlos16196 - this is likely because you're presenting inside a `UINavigationController`.

As of iOS 7 (I think?), a navigation controller defines the orientation for it's child view controllers. You'll need to subclass `UINavigationController`, override these methods, then set JSQMessagesVC as the root.

The reason this category works, is because it will apply to all VCs (thus it applies to navigation controllers).
