### ISSUE TITLE
How to add custom buttons to chat bubble 

### ISSUE THREAD

**Issue by smartsanja2013** [jessesquires/JSQMessagesViewController#986]
First I'd like to send my big thanks to the developer. This is a great controller. I am working on an app using Pusher and JSQMessagesViewController. 
I have a requirement to add custom buttons at the bottom of the chat bubble. The message type would be text JSQMessage with those two buttons 
![screen1136x1136](https://cloud.githubusercontent.com/assets/12458727/7650852/24ea9f20-fb18-11e4-8b11-73dc11726b4a.jpeg)

Any ideas please?

**Comment by alexruperez** [comment]
:+1:

**Comment by jerrypainter** [comment]
same question here

**Comment by atfermin** [comment]
+1. In my case I want a button / activity indicator on the side

![screen shot 2015-06-11 at 1 48 09 pm](https://cloud.githubusercontent.com/assets/6512090/8100584/9b9d6aac-1040-11e5-89f7-37d433ea30e8.png)

**Comment by brianhu** [comment]
want to know too

**Comment by dealaus** [comment]
Anyone get anywhere on this? I'm struggling to put the pieces together.

**Comment by jessesquires** [comment]
Hey guys — try checking out the existing threads that discuss customizing cells. :smile: 

https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+%5BCustom+Cells%5D+is%3Aclosed

**Comment by apwelsh** [comment]
Anyone make any progress on this?  I am trying to add two buttons too.  I tried creating a media item, which works for me, except that I cannot control with width of the text unless I set a fixed width, and cannot find out any way to to determine the maximum width, of how to configure constraints, since the media items appear to require a fixed size.

I try with customizing the default messaging cell by adding buttons below the text but that breaks the constraints.  I hope someone has figured this out.

**Comment by eliburke** [comment]
@apwelsh you should be able to use the width of the collection view, and set it on individual custom media view cells in e.g. cellForItemAtIndexPath. Then you can use autolayout or manually lay out your buttons. There may be some cases where you will need to invalidate the collection's stored cell sizes. #1257 may have some useful tips.

(I'll add that I have not done this-- my app does not use interactive buttons or variable width messages, but I believe it will work)

**Comment by apwelsh** [comment]
I implemented a hack whereby I use the screen width, and subtract 80 to get the max label width.  I dont like this because it is not based on the cell's container.  I am not the most skilled when it comes to working with these collection views, and suspect i must be missing something.  For my own views, I use constraints, so the widths of controls are set dynamically based on the oarent container, message content.  The challenge here is that the media type references  the mediaViewDisplaySize methid to determine the size if the media cell, and sets a hard size accordingly.  

Rather than resize the media using reflections to locate the parent container, I am curious if constraints assigned to my custom JSQMessageMediaData will be honored by the parent or if I will have to create the constraints against parent view....

My current hack of using the screen is working for now. It just isnt really the right way to do it in my opinion, as it depends on the layout being static, and manipulation if I ever want to change the look and feel.

**Comment by saikrishnaburra** [comment]
I have added target function for the button in the message...but the function is not getting executed...when clicked the  button.
